return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.15.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 62,
  height = 40,
  tilewidth = 64,
  tileheight = 64,
  nextobjectid = 135,
  properties = {},
  tilesets = {
    {
      name = "couloirs 64px",
      firstgid = 1,
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "couloirs_64px.png",
      imagewidth = 832,
      imageheight = 832,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 169,
      tiles = {
        {
          id = 84,
          properties = {
            ["collidable"] = "true"
          }
        },
        {
          id = 97,
          properties = {
            ["collidable"] = "true"
          }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Calque de Tile 1",
      x = 0,
      y = 0,
      width = 62,
      height = 40,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "YgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABVAAAAOQAAADkAAAA5AAAAOQAAADkAAABVAAAAVQAAAFUAAAA5AAAAOQAAAFUAAABiAAAAYgAAAFUAAAA5AAAAOQAAADkAAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAAA5AAAAOQAAADkAAAA5AAAAOQAAADkAAAA5AAAAOQAAADkAAAA5AAAAOQAAADkAAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAOQAAADkAAAA5AAAAYgAAAGIAAAA5AAAAOQAAADkAAAA5AAAAOQAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAGIAAABiAAAAYgAAAFUAAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAAA5AAAAVQAAAG8AAABvAAAAVQAAADkAAABVAAAAYgAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAADkAAABVAAAAYgAAAGIAAABiAAAAYgAAAFUAAAA5AAAAVQAAADkAAAA5AAAAOQAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABvAAAAbwAAADkAAABVAAAAYgAAAGIAAABiAAAAOQAAADkAAABVAAAAYgAAAGIAAABiAAAAYgAAADkAAAA5AAAAbwAAAG8AAABvAAAAVQAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAADkAAABiAAAAVQAAAG8AAABiAAAAOQAAAFUAAABvAAAAOQAAAFUAAABiAAAAYgAAAGIAAABiAAAAOQAAAFUAAABvAAAAbwAAAG8AAABvAAAAVQAAADkAAABVAAAAOQAAAFUAAABiAAAAYgAAADkAAAA5AAAAYgAAAGIAAABVAAAAYgAAADkAAABiAAAAYgAAAGIAAABiAAAAOQAAAFUAAABvAAAAbwAAAG8AAAA5AAAAOQAAAFUAAABvAAAAbwAAAG8AAABvAAAAOQAAAFUAAABVAAAAOQAAAGIAAABiAAAAOQAAADkAAABVAAAAOQAAAFUAAABVAAAAOQAAAG8AAABiAAAAOQAAAG8AAAA5AAAAYgAAAGIAAABiAAAAYgAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABiAAAAVQAAADkAAABiAAAAOQAAAGIAAABiAAAAVQAAAG8AAABvAAAAOQAAADkAAABvAAAAbwAAAFUAAABvAAAAOQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAABVAAAAYgAAAGIAAABiAAAAYgAAADkAAAA5AAAAYgAAAGIAAAA5AAAAbwAAAG8AAAA5AAAAYgAAAFUAAABVAAAAYgAAAGIAAABiAAAAOQAAAG8AAAA5AAAAVQAAADkAAABvAAAAbwAAAG8AAABvAAAAOQAAAFUAAABiAAAAYgAAADkAAABiAAAAOQAAAG8AAABiAAAAOQAAAG8AAAA5AAAAbwAAAG8AAABiAAAAYgAAADkAAABiAAAAYgAAAGIAAABiAAAAYgAAADkAAABiAAAAYgAAAGIAAABiAAAAOQAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAAFUAAABvAAAAbwAAAG8AAABvAAAAOQAAADkAAABvAAAAbwAAADkAAAA5AAAAOQAAADkAAABvAAAAYgAAAGIAAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABiAAAAYgAAAGIAAABiAAAAYgAAADkAAABVAAAAYgAAAG8AAABvAAAAOQAAAG8AAAA5AAAAOQAAAG8AAAA5AAAAOQAAAFUAAAA5AAAAOQAAAG8AAABvAAAAOQAAAG8AAABvAAAAbwAAAG8AAABvAAAAOQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAYgAAAGIAAABiAAAAVQAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAVQAAADkAAABvAAAAbwAAADkAAABVAAAAYgAAADkAAABVAAAAOQAAAG8AAABvAAAAbwAAAG8AAABvAAAAOQAAAGIAAABvAAAAOQAAAGIAAABiAAAAYgAAAGIAAABVAAAAVQAAADkAAAA5AAAAVQAAADkAAABVAAAAYgAAAGIAAAA5AAAAVQAAADkAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABiAAAAYgAAAGIAAAA5AAAAYgAAADkAAABVAAAAOQAAAGIAAABvAAAAbwAAAG8AAABVAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAbwAAADkAAABiAAAAYgAAADkAAABiAAAAYgAAAGIAAABvAAAAOQAAAFUAAAA5AAAAVQAAADkAAAA5AAAAVQAAAGIAAAA5AAAAbwAAADkAAAA5AAAAbwAAAG8AAABvAAAAbwAAAFUAAABiAAAAOQAAADkAAABiAAAAYgAAAFUAAABvAAAAbwAAADkAAABVAAAAOQAAAG8AAAA5AAAAVQAAADkAAABVAAAAOQAAAG8AAABvAAAAbwAAADkAAABvAAAAOQAAAFUAAAA5AAAAbwAAADkAAABiAAAAYgAAAGIAAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAAA5AAAAOQAAAG8AAABvAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAYgAAADkAAABiAAAAYgAAAGIAAABVAAAAbwAAADkAAABiAAAAYgAAAFUAAAA5AAAAYgAAAGIAAABiAAAAVQAAAG8AAAA5AAAAOQAAAG8AAABvAAAAVQAAADkAAABVAAAAOQAAAGIAAABVAAAAOQAAAFUAAABiAAAAOQAAAGIAAABiAAAAYgAAAFUAAAA5AAAAVQAAAFUAAAA5AAAAVQAAADkAAAA5AAAAOQAAAG8AAABvAAAAbwAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAADkAAABiAAAAYgAAAGIAAABVAAAAOQAAADkAAAA5AAAAVQAAAGIAAABvAAAAOQAAAG8AAABvAAAAbwAAAFUAAAA5AAAAOQAAAG8AAABvAAAAVQAAADkAAABvAAAAbwAAAG8AAABiAAAAOQAAAGIAAABiAAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAbwAAAFUAAAA5AAAAVQAAAG8AAAA5AAAAbwAAAG8AAABvAAAAVQAAADkAAABiAAAAYgAAADkAAABiAAAAYgAAADkAAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAVQAAADkAAABVAAAAOQAAAG8AAABvAAAAbwAAAGIAAAA5AAAAYgAAAGIAAABiAAAAbwAAADkAAABiAAAAVQAAAGIAAAA5AAAAYgAAAGIAAABiAAAAVQAAADkAAABVAAAAOQAAAFUAAABVAAAAOQAAAG8AAAA5AAAAbwAAAG8AAABVAAAAOQAAAFUAAAA5AAAAYgAAADkAAAA5AAAAYgAAAGIAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABiAAAAOQAAAG8AAABvAAAAOQAAAG8AAABvAAAAOQAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABiAAAAOQAAAFUAAAA5AAAAVQAAAFUAAAA5AAAAbwAAADkAAABvAAAAbwAAAG8AAAA5AAAAOQAAAG8AAABVAAAAbwAAADkAAABvAAAAbwAAAG8AAABVAAAAOQAAAFUAAAA5AAAAYgAAAGIAAABVAAAAOQAAAFUAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAOQAAADkAAABvAAAAbwAAAG8AAAA5AAAAYgAAAGIAAABiAAAAOQAAAG8AAAA5AAAAVQAAADkAAABVAAAAYgAAAGIAAAA5AAAAOQAAADkAAABVAAAAOQAAADkAAABVAAAAOQAAAG8AAAA5AAAAVQAAADkAAABiAAAAYgAAADkAAABVAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAbwAAAFUAAAA5AAAAVQAAAG8AAAA5AAAAVQAAADkAAABVAAAAOQAAADkAAABVAAAAYgAAAGIAAABiAAAAYgAAADkAAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAABvAAAAOQAAADkAAAA5AAAAOQAAAFUAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAG8AAABvAAAAOQAAAFUAAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAAA5AAAAYgAAADkAAABVAAAAOQAAAFUAAAA5AAAAYgAAADkAAABiAAAAYgAAADkAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAABiAAAAOQAAAGIAAAA5AAAAOQAAAFUAAABvAAAAbwAAAG8AAABvAAAAOQAAADkAAAA5AAAAOQAAAGIAAABiAAAAOQAAAFUAAAA5AAAAYgAAADkAAAA5AAAAVQAAAFUAAAA5AAAAYgAAAG8AAAA5AAAAVQAAADkAAABiAAAAOQAAAGIAAABiAAAAYgAAADkAAABiAAAAYgAAADkAAABVAAAAOQAAAFUAAABiAAAAVQAAADkAAABvAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAOQAAAG8AAABvAAAAOQAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAAG8AAAA5AAAAbwAAADkAAAA5AAAAYgAAAGIAAAA5AAAAVQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAbwAAAG8AAAA5AAAAVQAAADkAAABvAAAAOQAAADkAAABVAAAAVQAAADkAAABvAAAAOQAAADkAAABVAAAAOQAAAG8AAAA5AAAAOQAAAG8AAABvAAAAOQAAAG8AAABvAAAAOQAAAFUAAAA5AAAAYgAAAG8AAABiAAAAYgAAADkAAABiAAAAYgAAADkAAABiAAAAVQAAADkAAAA5AAAAVQAAADkAAAA5AAAAVQAAAGIAAAA5AAAAYgAAADkAAABiAAAAYgAAAGIAAAA5AAAAVQAAADkAAABvAAAAbwAAADkAAABVAAAAbwAAAG8AAABvAAAAbwAAADkAAABiAAAAYgAAAGIAAABiAAAAOQAAAFUAAABiAAAAOQAAAFUAAABVAAAAOQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAYgAAAGIAAAA5AAAAYgAAAGIAAAA5AAAAVQAAAGIAAABiAAAAYgAAADkAAABvAAAAOQAAAG8AAABvAAAAOQAAAG8AAABvAAAAOQAAAG8AAABiAAAAYgAAADkAAABVAAAAOQAAADkAAABVAAAAbwAAADkAAAA5AAAAOQAAADkAAABvAAAAbwAAADkAAABVAAAAYgAAAGIAAAA5AAAAOQAAAFUAAAA5AAAAYgAAAGIAAAA5AAAAOQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAAG8AAAA5AAAAVQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAbwAAADkAAABvAAAAbwAAADkAAABvAAAAbwAAADkAAABVAAAAbwAAAG8AAABvAAAAOQAAADkAAABVAAAAYgAAAGIAAAA5AAAAYgAAAGIAAABVAAAAbwAAAG8AAABvAAAAOQAAAFUAAAA5AAAAOQAAAGIAAAA5AAAAYgAAAGIAAABVAAAAOQAAAFUAAAA5AAAAYgAAAGIAAABvAAAAbwAAADkAAAA5AAAAVQAAADkAAABvAAAAbwAAADkAAABVAAAAOQAAAFUAAABVAAAAYgAAADkAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAOQAAAFUAAABiAAAAVQAAADkAAABVAAAAOQAAAFUAAABiAAAAYgAAAGIAAABiAAAAOQAAAFUAAABvAAAAbwAAAG8AAABvAAAAOQAAAFUAAABiAAAAYgAAAGIAAAA5AAAAVQAAADkAAAA5AAAAbwAAADkAAABvAAAAbwAAAFUAAAA5AAAAVQAAADkAAABvAAAAbwAAADkAAABVAAAAYgAAADkAAABiAAAAYgAAAGIAAABiAAAAOQAAAGIAAAA5AAAAVQAAAFUAAABvAAAAOQAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAAG8AAABVAAAAOQAAAFUAAAA5AAAAVQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAAG8AAABvAAAAbwAAADkAAABiAAAAYgAAAFUAAAA5AAAAVQAAAGIAAAA5AAAAYgAAADkAAABiAAAAVQAAADkAAABiAAAAYgAAAGIAAAA5AAAAOQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAbwAAADkAAABVAAAAYgAAADkAAABVAAAAYgAAAGIAAABiAAAAOQAAADkAAABVAAAAOQAAAGIAAABiAAAAVQAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAADkAAABVAAAAOQAAAFUAAABiAAAAYgAAAGIAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAVQAAAGIAAABiAAAAOQAAAG8AAABvAAAAVQAAADkAAABVAAAAbwAAADkAAABvAAAAOQAAAG8AAABVAAAAOQAAADkAAAA5AAAAbwAAADkAAABiAAAAYgAAAFUAAABiAAAAYgAAAGIAAABiAAAAOQAAAGIAAABvAAAAOQAAAFUAAABvAAAAbwAAAG8AAAA5AAAAOQAAAFUAAAA5AAAAbwAAAG8AAABVAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAOQAAAGIAAAA5AAAAVQAAAG8AAABvAAAAbwAAAGIAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAABVAAAAbwAAAG8AAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAADkAAABVAAAAOQAAAG8AAABvAAAAVQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAbwAAADkAAAA5AAAAYgAAAGIAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAYgAAADkAAABVAAAAYgAAAFUAAAA5AAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAbwAAADkAAABiAAAAYgAAAGIAAAA5AAAAVQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAOQAAAFUAAAA5AAAAVQAAADkAAABiAAAAOQAAAGIAAABiAAAAYgAAAGIAAABiAAAAVQAAADkAAABvAAAAbwAAAG8AAABvAAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAOQAAAFUAAABvAAAAVQAAADkAAABVAAAAOQAAAGIAAAA5AAAAVQAAADkAAABVAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAYgAAADkAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAYgAAAGIAAAA5AAAAVQAAADkAAABVAAAAOQAAAG8AAAA5AAAAbwAAAG8AAABvAAAAbwAAAG8AAABVAAAAOQAAAFUAAABiAAAAYgAAAGIAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABiAAAAOQAAADkAAABVAAAAYgAAADkAAABiAAAAYgAAAGIAAAA5AAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABiAAAAYgAAAGIAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAOQAAAG8AAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAABvAAAAbwAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAADkAAABVAAAAYgAAAGIAAABiAAAAOQAAAFUAAAA5AAAAVQAAAG8AAABvAAAAbwAAAGIAAAA5AAAAYgAAAGIAAABiAAAAOQAAAG8AAAA5AAAAYgAAAGIAAABvAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAOQAAAGIAAAA5AAAAVQAAADkAAABVAAAAbwAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAOQAAAFUAAABvAAAAbwAAAG8AAAA5AAAAYgAAADkAAABVAAAAOQAAAFUAAAA5AAAAbwAAADkAAABvAAAAbwAAAG8AAAA5AAAAOQAAADkAAABvAAAAbwAAADkAAABVAAAAYgAAAGIAAABiAAAAOQAAAFUAAAA5AAAAbwAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAVQAAAGIAAABiAAAAOQAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAAA5AAAAYgAAAGIAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABiAAAAYgAAAFUAAAA5AAAAYgAAADkAAABiAAAAVQAAADkAAABvAAAAOQAAAFUAAAA5AAAAVQAAADkAAAA5AAAAVQAAADkAAAA5AAAAVQAAAGIAAABiAAAAYgAAAGIAAABiAAAAVQAAAGIAAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAbwAAAG8AAABVAAAAbwAAAG8AAAA5AAAAYgAAAGIAAABiAAAAVQAAAGIAAABVAAAAOQAAADkAAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABVAAAAOQAAADkAAAA5AAAAVQAAADkAAABvAAAAOQAAAG8AAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAADkAAABiAAAAOQAAADkAAABVAAAAbwAAAG8AAABvAAAAbwAAAG8AAABVAAAAbwAAADkAAABVAAAAYgAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAADkAAABiAAAAYgAAAGIAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAbwAAAG8AAABVAAAAbwAAAFUAAAA5AAAAYgAAAGIAAABVAAAAOQAAAGIAAABiAAAAOQAAAGIAAABiAAAAYgAAADkAAABiAAAAVQAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAADkAAABiAAAAOQAAAGIAAABVAAAAOQAAAG8AAAA5AAAAOQAAAGIAAAA5AAAAVQAAAGIAAABiAAAAOQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAOQAAAG8AAABvAAAAbwAAAFUAAAA5AAAAYgAAADkAAABiAAAAYgAAAGIAAABVAAAAOQAAAGIAAAA5AAAAVQAAADkAAABvAAAAbwAAAFUAAAA5AAAAbwAAAG8AAAA5AAAAOQAAADkAAAA5AAAAOQAAADkAAABVAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAOQAAAG8AAAA5AAAAbwAAAFUAAAA5AAAAOQAAAFUAAAA5AAAAbwAAADkAAABVAAAAbwAAAG8AAAA5AAAAbwAAAG8AAABvAAAAbwAAAGIAAABiAAAAYgAAADkAAAA5AAAAVQAAAGIAAABVAAAAYgAAAFUAAAA5AAAAVQAAADkAAABvAAAAOQAAAG8AAABvAAAAbwAAAGIAAAA5AAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAYgAAAGIAAABiAAAAYgAAADkAAABiAAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAYgAAAGIAAABVAAAAOQAAAFUAAABiAAAAYgAAAGIAAABiAAAAYgAAADkAAAA5AAAAYgAAADkAAABVAAAAOQAAAGIAAABVAAAAOQAAAFUAAAA5AAAAVQAAAGIAAAA5AAAAbwAAAG8AAABvAAAAOQAAADkAAABiAAAAbwAAAFUAAABvAAAAYgAAADkAAABiAAAAYgAAAGIAAABiAAAAYgAAAFUAAAA5AAAAbwAAADkAAABiAAAAYgAAAGIAAAA5AAAAVQAAADkAAABvAAAAbwAAAG8AAABvAAAAOQAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAbwAAAFUAAAA5AAAAVQAAAG8AAABvAAAAbwAAAG8AAABvAAAAOQAAADkAAABvAAAAOQAAAFUAAAA5AAAAbwAAAGIAAAA5AAAAVQAAADkAAABVAAAAbwAAADkAAABVAAAAYgAAAGIAAABiAAAAOQAAAG8AAAA5AAAAYgAAADkAAABvAAAAOQAAAG8AAABvAAAAbwAAAG8AAABvAAAAYgAAAGIAAABiAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAYgAAAGIAAAA5AAAAVQAAADkAAABiAAAAYgAAAGIAAAA5AAAAVQAAADkAAABiAAAAYgAAAFUAAAA5AAAAVQAAADkAAABiAAAAOQAAAGIAAABiAAAAYgAAAGIAAABVAAAAVQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAAFUAAABvAAAAbwAAAG8AAAA5AAAAOQAAADkAAABvAAAAOQAAADkAAABiAAAAYgAAAFUAAABVAAAAOQAAADkAAABvAAAAbwAAAG8AAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAABvAAAAbwAAADkAAABVAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAOQAAADkAAAA5AAAAVQAAADkAAABiAAAAOQAAAG8AAAA5AAAAbwAAAG8AAABvAAAAbwAAAFUAAABVAAAAbwAAAG8AAABvAAAAbwAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAADkAAABiAAAAVQAAADkAAABVAAAAVQAAAFUAAABVAAAAVQAAADkAAAA5AAAAOQAAAG8AAABvAAAAYgAAAGIAAAA5AAAAYgAAAGIAAABiAAAAVQAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAADkAAABVAAAAYgAAAGIAAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAADkAAABVAAAAOQAAADkAAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAFUAAABiAAAAVQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAbwAAAG8AAABvAAAAOQAAADkAAABVAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAADkAAABvAAAAbwAAADkAAABvAAAAbwAAAG8AAABiAAAAVQAAADkAAAA5AAAAOQAAADkAAAA5AAAAYgAAAGIAAABvAAAAbwAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAOQAAAGIAAABVAAAAOQAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAVQAAAG8AAABVAAAAbwAAAG8AAABvAAAAbwAAADkAAABVAAAAYgAAAGIAAABiAAAAOQAAAGIAAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAOQAAAFUAAAA5AAAAYgAAAGIAAABVAAAAOQAAAG8AAABiAAAAYgAAAGIAAABiAAAAYgAAADkAAABvAAAAbwAAADkAAABVAAAAYgAAAGIAAABiAAAAYgAAAFUAAAA5AAAAVQAAADkAAAA5AAAAbwAAAFUAAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAVQAAAFUAAABiAAAAOQAAAFUAAABVAAAAVQAAAFUAAAA5AAAAVQAAAGIAAABvAAAAbwAAAG8AAAA5AAAAbwAAADkAAAA5AAAAYgAAAGIAAABiAAAAYgAAAFUAAABVAAAAYgAAAGIAAAA5AAAAVQAAADkAAABvAAAAbwAAAGIAAABiAAAAOQAAAG8AAABvAAAAbwAAAG8AAABvAAAAOQAAADkAAABiAAAAYgAAAGIAAABvAAAAbwAAAG8AAABvAAAAVQAAADkAAABVAAAAOQAAADkAAAA5AAAAYgAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABiAAAAVQAAAG8AAAA5AAAAYgAAAGIAAABiAAAAYgAAADkAAABiAAAAbwAAADkAAABVAAAAYgAAAGIAAABiAAAAOQAAAG8AAABvAAAAbwAAAG8AAABvAAAAVQAAAFUAAABvAAAAbwAAADkAAABVAAAAOQAAADkAAAA5AAAAbwAAAG8AAAA5AAAAOQAAAFUAAABiAAAAYgAAAGIAAABiAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAVQAAADkAAABiAAAAOQAAAGIAAABiAAAAVQAAADkAAABvAAAAOQAAAGIAAABiAAAAYgAAAGIAAABVAAAAOQAAAG8AAABVAAAAOQAAADkAAABvAAAAbwAAAG8AAABvAAAAOQAAAG8AAAA5AAAAVQAAAFUAAABvAAAAbwAAAG8AAAA5AAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAAA5AAAAOQAAAFUAAABVAAAAOQAAADkAAABiAAAAYgAAAGIAAABiAAAAYgAAAG8AAABvAAAAbwAAAG8AAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAOQAAAG8AAAA5AAAAOQAAADkAAABiAAAAYgAAAGIAAAA5AAAAbwAAAG8AAABvAAAAbwAAAGIAAABiAAAAYgAAAGIAAAA="
    },
    {
      type = "objectgroup",
      name = "sorties",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 580,
          y = 2,
          width = 60,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 836,
          y = 0,
          width = 58,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 642,
          y = 2,
          width = 62,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 706,
          y = 4,
          width = 60,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 2,
          width = 68,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1086,
          y = 2,
          width = 68,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 2,
          width = 64,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1474,
          y = 2,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1546,
          y = 12,
          width = 52,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1600,
          y = 0,
          width = 62,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1664,
          y = 0,
          width = 62,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2052,
          y = 4,
          width = 60,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2120,
          y = 6,
          width = 60,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2184,
          y = 8,
          width = 58,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2242,
          y = 6,
          width = 58,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2308,
          y = 2,
          width = 60,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2366,
          y = 4,
          width = 62,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2428,
          y = 6,
          width = 68,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2496,
          y = 2,
          width = 68,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2564,
          y = 10,
          width = 68,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2630,
          y = 4,
          width = 64,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2698,
          y = 2,
          width = 58,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2762,
          y = 4,
          width = 58,
          height = 70,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2822,
          y = 2,
          width = 56,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3266,
          y = 8,
          width = 64,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3334,
          y = 8,
          width = 54,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3394,
          y = 6,
          width = 60,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3590,
          y = 4,
          width = 58,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3654,
          y = 10,
          width = 60,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3714,
          y = 6,
          width = 62,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3774,
          y = 2,
          width = 68,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3842,
          y = 4,
          width = 60,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3904,
          y = 4,
          width = 62,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3912,
          y = 66,
          width = 56,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3906,
          y = 138,
          width = 58,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3906,
          y = 452,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3904,
          y = 516,
          width = 62,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3912,
          y = 580,
          width = 58,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3912,
          y = 650,
          width = 56,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3908,
          y = 702,
          width = 56,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3908,
          y = 766,
          width = 56,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3908,
          y = 1158,
          width = 56,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3908,
          y = 1222,
          width = 54,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3906,
          y = 1282,
          width = 64,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3904,
          y = 1598,
          width = 58,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3908,
          y = 1664,
          width = 58,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3906,
          y = 1732,
          width = 62,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3902,
          y = 1796,
          width = 66,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3906,
          y = 1858,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3902,
          y = 1924,
          width = 64,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3902,
          y = 1990,
          width = 66,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3904,
          y = 2252,
          width = 66,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 70,
          width = 66,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4,
          y = 132,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4,
          y = 198,
          width = 60,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4,
          y = 458,
          width = 56,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4,
          y = 520,
          width = 56,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10,
          y = 590,
          width = 50,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2,
          y = 642,
          width = 56,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4,
          y = 710,
          width = 58,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 768,
          width = 66,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 826,
          width = 50,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6,
          y = 1218,
          width = 60,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1278,
          width = 64,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1338,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2,
          y = 1404,
          width = 60,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4,
          y = 1460,
          width = 58,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1524,
          width = 62,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 4,
          y = 1590,
          width = 56,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 1662,
          width = 52,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2,
          y = 1862,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2,
          y = 1922,
          width = 58,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1986,
          width = 60,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8,
          y = 2056,
          width = 52,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2,
          y = 2438,
          width = 62,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 2506,
          width = 66,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 68,
          y = 2504,
          width = 60,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 124,
          y = 2502,
          width = 72,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 198,
          y = 2500,
          width = 58,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 2506,
          width = 64,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 316,
          y = 2508,
          width = 68,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 392,
          y = 2502,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 450,
          y = 2498,
          width = 62,
          height = 74,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 2504,
          width = 64,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 706,
          y = 2504,
          width = 64,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 770,
          y = 2504,
          width = 62,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 2510,
          width = 60,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 892,
          y = 2504,
          width = 68,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 2496,
          width = 64,
          height = 82,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 2498,
          width = 64,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1728,
          y = 2496,
          width = 70,
          height = 78,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1794,
          y = 2498,
          width = 64,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2180,
          y = 2500,
          width = 60,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2238,
          y = 2498,
          width = 70,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2304,
          y = 2496,
          width = 64,
          height = 74,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2368,
          y = 2502,
          width = 66,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2432,
          y = 2502,
          width = 64,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2882,
          y = 2490,
          width = 62,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2942,
          y = 2488,
          width = 66,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3010,
          y = 2492,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3072,
          y = 2492,
          width = 62,
          height = 82,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3130,
          y = 2492,
          width = 68,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3390,
          y = 2494,
          width = 66,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3450,
          y = 2490,
          width = 70,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3516,
          y = 2488,
          width = 68,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3582,
          y = 2498,
          width = 62,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3644,
          y = 2506,
          width = 64,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "spawns_hunter",
      visible = true,
      opacity = 0.9,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 124,
          name = "",
          type = "",
          shape = "rectangle",
          x = 962.667,
          y = 706.667,
          width = 61.3333,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3268,
          y = 640,
          width = 58,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1854.55,
          y = 1215.15,
          width = 63.6364,
          height = 60.6061,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "",
          type = "",
          shape = "rectangle",
          x = 893.939,
          y = 2175.76,
          width = 69.697,
          height = 63.6364,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3200,
          y = 2240,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "spawns_ghost",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1340,
          width = 60,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3592,
          y = 1348,
          width = 52,
          height = 44,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2052,
          y = 2364,
          width = 60,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2052,
          y = 304,
          width = 60,
          height = 76,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
