return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.15.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 64,
  height = 42,
  tilewidth = 64,
  tileheight = 64,
  nextobjectid = 135,
  properties = {},
  tilesets = {
    {
      name = "couloirs_64px",
      firstgid = 1,
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "couloirs_64px.png",
      imagewidth = 832,
      imageheight = 832,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 169,
      tiles = {
        {
          id = 84,
          properties = {
            ["collidable"] = "true"
          }
        },
        {
          id = 97,
          properties = {
            ["collidable"] = "true"
          }
        },
        {
          id = 136,
          properties = {
            ["collidable"] = "true"
          }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Calque de Tile 1",
      x = 0,
      y = 0,
      width = 64,
      height = 42,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "iQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAFUAAABvAAAAbwAAAG8AAABvAAAAbwAAAFUAAABVAAAAVQAAAG8AAABvAAAAVQAAAGIAAABiAAAAVQAAAG8AAABvAAAAbwAAAG8AAABiAAAAYgAAAGIAAABiAAAAYgAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABvAAAAbwAAAG8AAABiAAAAYgAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAIkAAACJAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABiAAAAYgAAAGIAAABVAAAAOQAAAGIAAABiAAAAYgAAAGIAAABiAAAAOQAAAFUAAABvAAAAbwAAAFUAAAA5AAAAVQAAAGIAAAA5AAAAbwAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAAGIAAABiAAAAYgAAAGIAAABVAAAAOQAAAFUAAAA5AAAAOQAAADkAAAA5AAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAOQAAAFUAAAA5AAAAbwAAAG8AAAA5AAAAVQAAAGIAAABiAAAAYgAAADkAAACJAAAAiQAAADkAAABVAAAAYgAAAGIAAABiAAAAYgAAADkAAAA5AAAAbwAAAG8AAABvAAAAVQAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAADkAAABiAAAAVQAAADkAAABiAAAAOQAAAFUAAABvAAAAOQAAAFUAAABiAAAAYgAAAGIAAABiAAAAOQAAAFUAAABvAAAAbwAAAG8AAABvAAAAVQAAADkAAABVAAAAOQAAAFUAAABiAAAAYgAAADkAAAA5AAAAYgAAAGIAAABVAAAAYgAAADkAAABiAAAAYgAAAGIAAABiAAAAOQAAAFUAAABvAAAAbwAAAG8AAAA5AAAAiQAAAIkAAAA5AAAAVQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAAFUAAAA5AAAAYgAAAGIAAAA5AAAAOQAAAFUAAAA5AAAAVQAAAFUAAAA5AAAAbwAAAGIAAAA5AAAAbwAAADkAAABiAAAAYgAAAGIAAABiAAAAbwAAAG8AAABvAAAAbwAAADkAAABVAAAAOQAAAGIAAABVAAAAOQAAAGIAAAA5AAAAYgAAAGIAAABVAAAAbwAAAG8AAAA5AAAAOQAAAG8AAABvAAAAVQAAAG8AAAA5AAAAbwAAAG8AAABvAAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAAIkAAACJAAAAVQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAOQAAAGIAAABiAAAAOQAAAG8AAABvAAAAOQAAAGIAAABVAAAAVQAAAGIAAABiAAAAYgAAADkAAABvAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAbwAAADkAAABVAAAAYgAAAGIAAAA5AAAAYgAAADkAAABvAAAAYgAAADkAAABvAAAAOQAAAG8AAABvAAAAYgAAAGIAAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAAA5AAAAYgAAAGIAAABiAAAAYgAAADkAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAACJAAAAiQAAAFUAAABvAAAAbwAAAG8AAABvAAAAOQAAADkAAABvAAAAbwAAADkAAAA5AAAAOQAAADkAAABvAAAAYgAAAGIAAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABiAAAAYgAAAGIAAABiAAAAYgAAADkAAABVAAAAYgAAAG8AAABvAAAAOQAAAG8AAAA5AAAAOQAAAG8AAAA5AAAAOQAAAFUAAAA5AAAAOQAAAG8AAABvAAAAOQAAAG8AAABvAAAAbwAAAG8AAABvAAAAOQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAiQAAAIkAAABiAAAAYgAAAGIAAABVAAAAOQAAAFUAAAA5AAAAYgAAAGIAAABiAAAAYgAAADkAAABVAAAAOQAAAG8AAABvAAAAOQAAAFUAAABiAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAbwAAAG8AAAA5AAAAYgAAAG8AAAA5AAAAYgAAAGIAAABiAAAAYgAAAFUAAABVAAAAOQAAADkAAABVAAAAOQAAAFUAAABiAAAAYgAAADkAAABVAAAAOQAAAGIAAAA5AAAAVQAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAADkAAABiAAAAOQAAAFUAAAA5AAAAYgAAAIkAAACJAAAAbwAAAG8AAABvAAAAVQAAADkAAABVAAAAOQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAYgAAAGIAAAA5AAAAYgAAAGIAAABiAAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAOQAAAFUAAABiAAAAOQAAAG8AAAA5AAAAOQAAAG8AAABvAAAAbwAAAG8AAABVAAAAYgAAADkAAAA5AAAAYgAAAGIAAABVAAAAbwAAAG8AAAA5AAAAVQAAADkAAABvAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAbwAAAG8AAAA5AAAAbwAAADkAAABVAAAAOQAAAG8AAACJAAAAiQAAADkAAABiAAAAYgAAAGIAAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAAA5AAAAOQAAAG8AAABvAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAYgAAADkAAABiAAAAYgAAAGIAAABVAAAAbwAAADkAAABiAAAAYgAAAFUAAAA5AAAAYgAAAGIAAABiAAAAVQAAAG8AAAA5AAAAOQAAAG8AAABvAAAAVQAAADkAAABVAAAAOQAAAGIAAABVAAAAOQAAAFUAAABiAAAAOQAAAGIAAABiAAAAYgAAAFUAAAA5AAAAVQAAAFUAAAA5AAAAVQAAADkAAAA5AAAAiQAAAIkAAAA5AAAAbwAAAG8AAABvAAAAOQAAAG8AAABvAAAAbwAAAG8AAABvAAAAOQAAAGIAAABiAAAAYgAAAFUAAAA5AAAAOQAAADkAAABVAAAAYgAAAG8AAAA5AAAAbwAAAG8AAABvAAAAVQAAADkAAAA5AAAAbwAAAG8AAABVAAAAOQAAAG8AAABvAAAAbwAAAGIAAAA5AAAAYgAAAGIAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAVQAAADkAAABVAAAAbwAAADkAAABvAAAAbwAAAG8AAABVAAAAOQAAAGIAAABiAAAAOQAAAGIAAABiAAAAOQAAAIkAAACJAAAAOQAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAFUAAAA5AAAAVQAAADkAAABvAAAAbwAAAG8AAABiAAAAOQAAAGIAAABiAAAAYgAAAG8AAAA5AAAAYgAAAFUAAABiAAAAOQAAAGIAAABiAAAAYgAAAFUAAAA5AAAAVQAAADkAAABVAAAAVQAAADkAAABvAAAAOQAAAG8AAABvAAAAVQAAADkAAABVAAAAOQAAAGIAAAA5AAAAOQAAAGIAAABiAAAAYgAAADkAAABVAAAAOQAAAFUAAAA5AAAAYgAAADkAAABvAAAAbwAAADkAAABvAAAAbwAAADkAAACJAAAAiQAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABiAAAAOQAAAFUAAAA5AAAAVQAAAFUAAAA5AAAAbwAAADkAAABvAAAAbwAAAG8AAAA5AAAAOQAAAG8AAABVAAAAbwAAADkAAABvAAAAbwAAAG8AAABVAAAAOQAAAFUAAAA5AAAAYgAAAGIAAABVAAAAOQAAAFUAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAOQAAADkAAABvAAAAbwAAAG8AAAA5AAAAYgAAAGIAAABiAAAAOQAAAG8AAAA5AAAAVQAAADkAAABVAAAAYgAAAGIAAAA5AAAAiQAAAIkAAAA5AAAAOQAAAFUAAAA5AAAAOQAAAFUAAAA5AAAAbwAAADkAAABVAAAAOQAAAGIAAABiAAAAOQAAAFUAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAG8AAABvAAAAVQAAADkAAABVAAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAOQAAAFUAAABiAAAAYgAAAGIAAABiAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAAG8AAABvAAAAOQAAAIkAAACJAAAAOQAAADkAAABVAAAAYgAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAbwAAADkAAABVAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAOQAAAGIAAAA5AAAAVQAAADkAAABVAAAAOQAAAGIAAAA5AAAAYgAAAGIAAAA5AAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAYgAAADkAAABiAAAAOQAAADkAAABVAAAAbwAAAG8AAABvAAAAbwAAADkAAAA5AAAAOQAAADkAAABiAAAAYgAAADkAAABVAAAAOQAAAGIAAAA5AAAAOQAAAFUAAACJAAAAiQAAAFUAAAA5AAAAYgAAAG8AAAA5AAAAVQAAADkAAABiAAAAOQAAAGIAAABiAAAAYgAAADkAAABiAAAAYgAAADkAAABVAAAAOQAAAFUAAABiAAAAVQAAADkAAABvAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAOQAAAG8AAABvAAAAOQAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAAG8AAAA5AAAAbwAAADkAAAA5AAAAYgAAAGIAAAA5AAAAVQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAbwAAAG8AAAA5AAAAVQAAADkAAABvAAAAOQAAADkAAABVAAAAiQAAAIkAAABVAAAAOQAAAG8AAAA5AAAAOQAAAFUAAAA5AAAAbwAAADkAAAA5AAAAbwAAAG8AAAA5AAAAbwAAAG8AAAA5AAAAVQAAADkAAABiAAAAbwAAAGIAAABiAAAAOQAAAGIAAABiAAAAOQAAAGIAAABVAAAAOQAAADkAAABVAAAAOQAAADkAAABVAAAAYgAAADkAAABiAAAAOQAAAGIAAABiAAAAYgAAADkAAABVAAAAOQAAAG8AAABvAAAAOQAAAFUAAABvAAAAbwAAAG8AAABvAAAAOQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAVQAAAGIAAAA5AAAAVQAAAIkAAACJAAAAVQAAADkAAABiAAAAYgAAAGIAAABiAAAAOQAAAGIAAABiAAAAOQAAAGIAAABiAAAAOQAAAFUAAABiAAAAYgAAAGIAAAA5AAAAbwAAADkAAABvAAAAbwAAADkAAABvAAAAbwAAADkAAABvAAAAYgAAAGIAAAA5AAAAVQAAADkAAAA5AAAAVQAAAG8AAAA5AAAAbwAAADkAAABvAAAAbwAAAG8AAAA5AAAAVQAAAGIAAABiAAAAOQAAADkAAABVAAAAOQAAAGIAAABiAAAAOQAAADkAAABvAAAAbwAAAG8AAABvAAAAOQAAAFUAAABvAAAAOQAAAFUAAACJAAAAiQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAbwAAADkAAABvAAAAbwAAADkAAABvAAAAbwAAADkAAABVAAAAbwAAAG8AAABvAAAAOQAAADkAAABVAAAAYgAAAGIAAAA5AAAAYgAAAGIAAABVAAAAOQAAAG8AAABvAAAAOQAAAFUAAAA5AAAAOQAAAGIAAAA5AAAAYgAAAGIAAABVAAAAOQAAAFUAAAA5AAAAYgAAAGIAAABvAAAAbwAAADkAAAA5AAAAVQAAADkAAABvAAAAbwAAADkAAABVAAAAOQAAAFUAAABVAAAAYgAAADkAAABiAAAAYgAAAGIAAABiAAAAiQAAAIkAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAAA5AAAAVQAAAGIAAABVAAAAOQAAAFUAAAA5AAAAVQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAVQAAAG8AAABvAAAAOQAAAG8AAABvAAAAVQAAAGIAAABiAAAAYgAAADkAAABVAAAAOQAAADkAAABvAAAAOQAAAG8AAABvAAAAVQAAADkAAABVAAAAOQAAAG8AAABvAAAAOQAAAFUAAABiAAAAOQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAYgAAADkAAABVAAAAVQAAAG8AAAA5AAAAbwAAAG8AAABvAAAAbwAAAIkAAACJAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAOQAAAFUAAABvAAAAVQAAADkAAABVAAAAOQAAAFUAAABvAAAAbwAAAG8AAABvAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAABvAAAAbwAAAG8AAAA5AAAAYgAAAGIAAABVAAAAOQAAAFUAAABiAAAAOQAAAGIAAAA5AAAAYgAAAFUAAAA5AAAAYgAAAGIAAABiAAAAbwAAADkAAABvAAAAbwAAAG8AAABvAAAAOQAAAG8AAAA5AAAAVQAAAGIAAAA5AAAAVQAAAGIAAABiAAAAYgAAADkAAACJAAAAiQAAADkAAABVAAAAOQAAAGIAAABiAAAAVQAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAADkAAABVAAAAOQAAAFUAAABiAAAAYgAAAGIAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAVQAAAGIAAABiAAAAOQAAAG8AAABvAAAAVQAAADkAAABVAAAAbwAAADkAAABvAAAAOQAAAG8AAABVAAAAOQAAAG8AAABvAAAAbwAAADkAAABiAAAAYgAAAFUAAABiAAAAYgAAAGIAAABiAAAAOQAAAGIAAABvAAAAOQAAAFUAAABvAAAAbwAAAG8AAAA5AAAAiQAAAIkAAAA5AAAAVQAAADkAAABvAAAAbwAAAFUAAAA5AAAAVQAAADkAAABvAAAAbwAAAG8AAAA5AAAAYgAAADkAAABVAAAAbwAAAG8AAABvAAAAYgAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAAFUAAABvAAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAYgAAAGIAAABiAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABVAAAAbwAAAG8AAABvAAAAbwAAADkAAABvAAAAOQAAADkAAABiAAAAYgAAAGIAAAA5AAAAVQAAAIkAAACJAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAGIAAAA5AAAAVQAAAGIAAABVAAAAOQAAAG8AAAA5AAAAVQAAADkAAABVAAAAOQAAAG8AAAA5AAAAYgAAAGIAAABiAAAAOQAAAFUAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAYgAAADkAAABiAAAAYgAAAGIAAABiAAAAYgAAAFUAAAA5AAAAbwAAAG8AAABvAAAAbwAAAFUAAACJAAAAiQAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAOQAAAFUAAABvAAAAVQAAADkAAABVAAAAOQAAAGIAAAA5AAAAVQAAADkAAABVAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAYgAAADkAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAYgAAAGIAAAA5AAAAVQAAADkAAABVAAAAOQAAAG8AAAA5AAAAbwAAAG8AAABvAAAAbwAAAG8AAABVAAAAOQAAAFUAAABiAAAAYgAAAGIAAABVAAAAiQAAAIkAAAA5AAAAVQAAADkAAABVAAAAOQAAAGIAAAA5AAAAOQAAAFUAAABiAAAAOQAAAGIAAABiAAAAYgAAADkAAABvAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAVQAAADkAAABVAAAAOQAAAG8AAAA5AAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAAG8AAABvAAAAOQAAAFUAAAA5AAAAYgAAAGIAAABiAAAAOQAAAFUAAABiAAAAYgAAAGIAAAA5AAAAVQAAADkAAABVAAAAbwAAAG8AAABvAAAAYgAAAIkAAACJAAAAOQAAAGIAAABiAAAAYgAAADkAAABvAAAAOQAAAGIAAABiAAAAbwAAADkAAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAbwAAAG8AAABvAAAAOQAAAFUAAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAbwAAAG8AAABvAAAAOQAAAGIAAAA5AAAAVQAAADkAAABVAAAAOQAAAG8AAACJAAAAiQAAADkAAABvAAAAbwAAAG8AAAA5AAAAOQAAADkAAABvAAAAbwAAADkAAABVAAAAYgAAAGIAAABiAAAAOQAAAFUAAAA5AAAAbwAAADkAAABVAAAAOQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAVQAAAGIAAABiAAAAOQAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAAA5AAAAYgAAAGIAAABiAAAAOQAAAFUAAAA5AAAAVQAAADkAAABiAAAAYgAAAFUAAAA5AAAAYgAAADkAAABiAAAAVQAAADkAAABvAAAAOQAAAFUAAAA5AAAAVQAAADkAAAA5AAAAiQAAAIkAAABVAAAAOQAAADkAAABVAAAAYgAAAGIAAABiAAAAYgAAAGIAAABVAAAAYgAAAG8AAABvAAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABvAAAAbwAAAG8AAABvAAAAOQAAAFUAAABvAAAAbwAAADkAAABiAAAAYgAAAGIAAABVAAAAYgAAAFUAAAA5AAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABVAAAAOQAAAG8AAAA5AAAAbwAAAFUAAAA5AAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAOQAAAIkAAACJAAAAVQAAADkAAAA5AAAAVQAAAG8AAABvAAAAbwAAAG8AAABvAAAAVQAAAG8AAAA5AAAAVQAAAGIAAAA5AAAAVQAAADkAAABiAAAAYgAAAGIAAAA5AAAAYgAAAGIAAABiAAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAVQAAAG8AAABVAAAAOQAAAGIAAABiAAAAVQAAADkAAABiAAAAYgAAADkAAABiAAAAYgAAAGIAAAA5AAAAYgAAAFUAAAA5AAAAVQAAADkAAABiAAAAYgAAAGIAAAA5AAAAYgAAADkAAABiAAAAVQAAADkAAACJAAAAiQAAAG8AAAA5AAAAOQAAAGIAAAA5AAAAVQAAAGIAAABiAAAAOQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAOQAAAG8AAABvAAAAbwAAAFUAAAA5AAAAYgAAADkAAABiAAAAYgAAAGIAAABVAAAAOQAAAGIAAAA5AAAAVQAAADkAAABvAAAAbwAAAFUAAAA5AAAAbwAAAG8AAAA5AAAAbwAAAG8AAABvAAAAOQAAAG8AAABVAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAOQAAAG8AAAA5AAAAbwAAAFUAAAA5AAAAiQAAAIkAAAA5AAAAVQAAADkAAABvAAAAOQAAAFUAAABvAAAAbwAAADkAAABvAAAAbwAAAG8AAABvAAAAYgAAAGIAAABiAAAAOQAAADkAAABVAAAAYgAAAFUAAABiAAAAVQAAADkAAABVAAAAOQAAAG8AAAA5AAAAbwAAAG8AAABvAAAAYgAAADkAAABvAAAAOQAAAFUAAAA5AAAAVQAAADkAAABiAAAAYgAAAGIAAABiAAAAOQAAAGIAAABVAAAAOQAAAFUAAAA5AAAAVQAAADkAAABiAAAAYgAAAFUAAAA5AAAAVQAAAGIAAABiAAAAYgAAAGIAAABiAAAAOQAAAIkAAACJAAAAOQAAAGIAAAA5AAAAVQAAADkAAABiAAAAVQAAADkAAABVAAAAOQAAAFUAAABiAAAAOQAAAG8AAABvAAAAbwAAADkAAAA5AAAAYgAAAG8AAABVAAAAbwAAAGIAAAA5AAAAYgAAAGIAAABiAAAAYgAAAGIAAABVAAAAOQAAAG8AAAA5AAAAYgAAAGIAAABiAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAbwAAADkAAABvAAAAVQAAADkAAABVAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABVAAAAOQAAAFUAAABvAAAAbwAAAG8AAABvAAAAbwAAADkAAACJAAAAiQAAADkAAABvAAAAOQAAAFUAAAA5AAAAbwAAAGIAAAA5AAAAVQAAADkAAABVAAAAbwAAADkAAABVAAAAYgAAAGIAAABiAAAAOQAAAG8AAAA5AAAAYgAAADkAAABvAAAAOQAAAG8AAABvAAAAbwAAAG8AAABvAAAAYgAAAGIAAABiAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAYgAAAGIAAAA5AAAAVQAAADkAAABiAAAAYgAAAGIAAAA5AAAAVQAAADkAAABiAAAAYgAAAFUAAAA5AAAAVQAAADkAAABiAAAAOQAAAGIAAABiAAAAYgAAAGIAAABVAAAAiQAAAIkAAABVAAAAYgAAAGIAAABiAAAAYgAAADkAAABvAAAAOQAAAFUAAAA5AAAAVQAAADkAAABVAAAAVQAAAG8AAABvAAAAbwAAADkAAAA5AAAAOQAAAG8AAAA5AAAAOQAAAGIAAABiAAAAVQAAAFUAAAA5AAAAOQAAAG8AAABvAAAAbwAAADkAAABiAAAAYgAAAGIAAABiAAAAYgAAAG8AAABvAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABvAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABVAAAAOQAAAGIAAAA5AAAAbwAAADkAAABvAAAAbwAAAG8AAABvAAAAVQAAAIkAAACJAAAAVQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABiAAAAYgAAAGIAAAA5AAAAYgAAAFUAAAA5AAAAVQAAAFUAAABVAAAAVQAAAFUAAAA5AAAAOQAAADkAAABvAAAAbwAAAGIAAABiAAAAOQAAAGIAAABiAAAAYgAAAFUAAAA5AAAAbwAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAAGIAAABiAAAAOQAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAAA5AAAAVQAAADkAAABvAAAAOQAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAACJAAAAiQAAAFUAAABiAAAAVQAAAGIAAABiAAAAYgAAAGIAAAA5AAAAbwAAAG8AAABvAAAAOQAAAG8AAABVAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAADkAAABvAAAAbwAAADkAAABvAAAAbwAAAG8AAABiAAAAVQAAADkAAAA5AAAAOQAAADkAAAA5AAAAYgAAAGIAAABvAAAAbwAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAOQAAAGIAAABVAAAAOQAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAiQAAAIkAAABVAAAAbwAAAFUAAABvAAAAbwAAAG8AAABvAAAAOQAAAFUAAABiAAAAYgAAAGIAAAA5AAAAYgAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAAA5AAAAVQAAADkAAABiAAAAYgAAAFUAAAA5AAAAbwAAAGIAAABiAAAAYgAAAGIAAABiAAAAOQAAAG8AAABvAAAAOQAAAFUAAABiAAAAYgAAAGIAAABiAAAAVQAAADkAAABVAAAAOQAAADkAAABvAAAAVQAAADkAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABVAAAAVQAAAIkAAACJAAAAYgAAADkAAABVAAAAVQAAAFUAAABVAAAAOQAAAFUAAABiAAAAbwAAAG8AAABvAAAAOQAAAG8AAAA5AAAAOQAAAGIAAABiAAAAYgAAAGIAAABVAAAAVQAAAGIAAABiAAAAOQAAAFUAAAA5AAAAbwAAAG8AAABiAAAAYgAAADkAAABvAAAAbwAAAG8AAABvAAAAbwAAADkAAAA5AAAAYgAAAGIAAABiAAAAbwAAAG8AAABvAAAAbwAAAFUAAAA5AAAAVQAAADkAAAA5AAAAOQAAAGIAAAA5AAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAYgAAAFUAAACJAAAAiQAAAG8AAAA5AAAAYgAAAGIAAABiAAAAYgAAADkAAABiAAAAbwAAADkAAABVAAAAYgAAAGIAAABiAAAAOQAAADkAAABvAAAAbwAAAG8AAABvAAAAVQAAAFUAAABvAAAAbwAAADkAAABVAAAAOQAAADkAAAA5AAAAbwAAAG8AAAA5AAAAOQAAAFUAAABiAAAAYgAAAGIAAABiAAAAOQAAAG8AAABvAAAAbwAAADkAAABVAAAAVQAAADkAAABiAAAAOQAAAGIAAABiAAAAVQAAADkAAABvAAAAOQAAAGIAAABiAAAAYgAAAGIAAABVAAAAOQAAAG8AAABVAAAAiQAAAIkAAAA5AAAAOQAAAG8AAABvAAAAbwAAAG8AAAA5AAAAbwAAADkAAABVAAAAVQAAAG8AAABvAAAAbwAAADkAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAADkAAAA5AAAAVQAAAFUAAAA5AAAAOQAAAFUAAABVAAAAVQAAAFUAAABVAAAAbwAAAG8AAABvAAAAbwAAADkAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAAA5AAAAbwAAADkAAABvAAAAbwAAAFUAAABVAAAAVQAAADkAAABvAAAAbwAAAG8AAABvAAAAVQAAAFUAAABVAAAAVQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAA"
    },
    {
      type = "objectgroup",
      name = "sorties",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 644,
          y = 66,
          width = 60,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 900,
          y = 64,
          width = 58,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 706,
          y = 66,
          width = 62,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 770,
          y = 68,
          width = 60,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 66,
          width = 68,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1150,
          y = 66,
          width = 68,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 66,
          width = 64,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1538,
          y = 66,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1610,
          y = 76,
          width = 52,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1664,
          y = 64,
          width = 62,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1728,
          y = 64,
          width = 62,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2116,
          y = 68,
          width = 60,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2184,
          y = 70,
          width = 60,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2248,
          y = 72,
          width = 58,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2306,
          y = 70,
          width = 58,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2372,
          y = 66,
          width = 60,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2430,
          y = 68,
          width = 62,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2492,
          y = 70,
          width = 68,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2560,
          y = 66,
          width = 68,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2628,
          y = 74,
          width = 68,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2694,
          y = 68,
          width = 64,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2762,
          y = 66,
          width = 58,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2826,
          y = 68,
          width = 58,
          height = 70,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2886,
          y = 66,
          width = 56,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3330,
          y = 72,
          width = 64,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3398,
          y = 72,
          width = 54,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3458,
          y = 70,
          width = 60,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3654,
          y = 68,
          width = 58,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3718,
          y = 74,
          width = 60,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3778,
          y = 70,
          width = 62,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3838,
          y = 66,
          width = 68,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3906,
          y = 68,
          width = 60,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3968,
          y = 68,
          width = 62,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3976,
          y = 130,
          width = 56,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3970,
          y = 202,
          width = 58,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3970,
          y = 516,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3968,
          y = 580,
          width = 62,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3976,
          y = 644,
          width = 58,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3976,
          y = 714,
          width = 56,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3972,
          y = 766,
          width = 56,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3972,
          y = 830,
          width = 56,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3972,
          y = 1222,
          width = 56,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3972,
          y = 1286,
          width = 54,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3970,
          y = 1346,
          width = 64,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3968,
          y = 1662,
          width = 58,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3972,
          y = 1728,
          width = 58,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3970,
          y = 1796,
          width = 62,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3966,
          y = 1860,
          width = 66,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3970,
          y = 1922,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3966,
          y = 1988,
          width = 64,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3966,
          y = 2054,
          width = 66,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3968,
          y = 2316,
          width = 66,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 134,
          width = 66,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 68,
          y = 196,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 68,
          y = 262,
          width = 60,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 68,
          y = 522,
          width = 56,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 68,
          y = 584,
          width = 56,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 74,
          y = 654,
          width = 50,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66,
          y = 706,
          width = 56,
          height = 50,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 68,
          y = 774,
          width = 58,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 77,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 832,
          width = 66,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 890,
          width = 50,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 70,
          y = 1282,
          width = 60,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1342,
          width = 64,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1402,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66,
          y = 1468,
          width = 60,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 68,
          y = 1524,
          width = 58,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1588,
          width = 62,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 68,
          y = 1654,
          width = 56,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 1726,
          width = 52,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66,
          y = 1926,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66,
          y = 1986,
          width = 58,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 2050,
          width = 60,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 2120,
          width = 52,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66,
          y = 2502,
          width = 62,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 2570,
          width = 66,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 132,
          y = 2568,
          width = 60,
          height = 54,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 188,
          y = 2566,
          width = 72,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 262,
          y = 2564,
          width = 58,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 2570,
          width = 64,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 380,
          y = 2572,
          width = 68,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 456,
          y = 2566,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 514,
          y = 2562,
          width = 62,
          height = 74,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 2568,
          width = 64,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 770,
          y = 2568,
          width = 64,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 834,
          y = 2568,
          width = 62,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 2574,
          width = 60,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 956,
          y = 2568,
          width = 68,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 2560,
          width = 64,
          height = 82,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1600,
          y = 2562,
          width = 64,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1792,
          y = 2560,
          width = 70,
          height = 78,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1858,
          y = 2562,
          width = 64,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2244,
          y = 2564,
          width = 60,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2302,
          y = 2562,
          width = 70,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2368,
          y = 2560,
          width = 64,
          height = 74,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 112,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2432,
          y = 2566,
          width = 66,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2496,
          y = 2566,
          width = 64,
          height = 72,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2946,
          y = 2554,
          width = 62,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3006,
          y = 2552,
          width = 66,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3074,
          y = 2556,
          width = 64,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3136,
          y = 2556,
          width = 62,
          height = 82,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3194,
          y = 2556,
          width = 68,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3454,
          y = 2558,
          width = 66,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3514,
          y = 2554,
          width = 70,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3580,
          y = 2552,
          width = 68,
          height = 68,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3646,
          y = 2562,
          width = 62,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3708,
          y = 2570,
          width = 64,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "spawns_hunter",
      visible = true,
      opacity = 0.9,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 124,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1026.67,
          y = 770.667,
          width = 61.3333,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3332,
          y = 704,
          width = 58,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1918.55,
          y = 1279.15,
          width = 63.6364,
          height = 60.6061,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "",
          type = "",
          shape = "rectangle",
          x = 957.939,
          y = 2239.76,
          width = 69.697,
          height = 63.6364,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3264,
          y = 2304,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "spawns_ghost",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1404,
          width = 60,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 3656,
          y = 1412,
          width = 52,
          height = 44,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2116,
          y = 2428,
          width = 60,
          height = 56,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2116,
          y = 368,
          width = 60,
          height = 76,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
