return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.15.1",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 26,
  height = 26,
  tilewidth = 64,
  tileheight = 64,
  nextobjectid = 82,
  properties = {
     game_time = 90},
  tilesets = {
    {
      name = "couloirs 64px",
      firstgid = 1,
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "couloirs_64px.png",
      imagewidth = 832,
      imageheight = 832,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 169,
      tiles = {
        {
          id = 84,
          properties = {
            ["collidable"] = "true"
          }
        },
        {
          id = 136,
          properties = {
            ["collidable"] = "true"
          }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Calque de Tile 1",
      x = 0,
      y = 0,
      width = 26,
      height = 26,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "iQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAUwAAAFUAAABTAAAAVQAAAG0AAABtAAAAbQAAAFUAAABtAAAAcQAAAFUAAABVAAAAOQAAADkAAABVAAAAVwAAAFUAAABxAAAAcQAAAHEAAABxAAAAcQAAAFUAAABtAAAAiQAAAIkAAABxAAAAVQAAAHEAAAA2AAAAbQAAAFUAAABtAAAANgAAAFUAAABxAAAAOwAAADsAAAA9AAAAVQAAAG8AAABxAAAAOwAAAFUAAABxAAAAVQAAAFUAAABxAAAAVQAAAG0AAACJAAAAiQAAAHEAAAA2AAAAcQAAAFUAAABVAAAAbwAAAHEAAABVAAAAbwAAAFUAAABtAAAAVQAAAFcAAABVAAAAVwAAAFUAAABxAAAAbwAAAHEAAAA7AAAAOwAAAFUAAABvAAAAbQAAAIkAAACJAAAAOQAAAFUAAABtAAAAbwAAADYAAABVAAAAcQAAADYAAABxAAAANgAAAFUAAAA7AAAAcQAAADsAAABxAAAAbwAAAFUAAABVAAAAUwAAAFUAAABxAAAAOwAAAHEAAABVAAAAiQAAAIkAAABxAAAANgAAAFUAAABxAAAAVQAAAFUAAABxAAAAVQAAAFUAAABxAAAAVQAAAHEAAABVAAAAVQAAAHEAAABVAAAAbwAAAG8AAABxAAAAVQAAAFUAAABVAAAAcQAAAFUAAACJAAAAiQAAAFUAAABVAAAAVQAAAHEAAAA2AAAANgAAAHEAAAA2AAAAVQAAAHEAAABvAAAAcQAAADsAAABVAAAAcQAAAG8AAABVAAAAOQAAAFUAAAA7AAAAOwAAADsAAABxAAAAOwAAAIkAAACJAAAAbwAAADsAAABVAAAAVQAAAHEAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAcQAAADsAAABVAAAAcQAAAFUAAABxAAAAbwAAAHEAAABVAAAAVQAAAFcAAABVAAAAiQAAAIkAAABVAAAAcQAAADsAAABvAAAAcQAAADsAAABVAAAAOQAAADYAAAA2AAAANgAAAG8AAABxAAAAVQAAAFUAAABxAAAAbwAAAHEAAABVAAAAcQAAAG8AAABVAAAAVwAAAG8AAACJAAAAiQAAAFUAAABtAAAAVQAAAFUAAABVAAAAbQAAAFUAAABxAAAAVQAAAFUAAABVAAAAVQAAAHEAAABVAAAAbwAAAFUAAABxAAAAVQAAAG8AAABVAAAAcQAAAFUAAABVAAAAVQAAAIkAAACJAAAAbwAAAG0AAAA7AAAAOwAAADsAAABVAAAAOwAAAHEAAABVAAAAOwAAADsAAABvAAAAVQAAADsAAAA5AAAAbwAAAHEAAABVAAAAbQAAADsAAABxAAAAbwAAAG8AAABVAAAAiQAAAIkAAABxAAAAVQAAAFUAAABVAAAAcQAAADsAAABxAAAAVQAAAFUAAABxAAAAVQAAAHEAAABvAAAAcQAAAFUAAABVAAAAVQAAADsAAABxAAAAVQAAAFUAAABVAAAAcQAAAFUAAACJAAAAiQAAAHEAAAA7AAAAOwAAAFUAAABtAAAAVQAAAHEAAABVAAAAOwAAAHEAAABvAAAAOQAAAFUAAAA9AAAAOwAAADsAAAA7AAAAcQAAAHEAAAA7AAAAOwAAADsAAABxAAAAbwAAAIkAAACJAAAAVQAAAFUAAABxAAAAOwAAAFUAAAA7AAAAcQAAAFUAAABxAAAAVQAAAFMAAABVAAAAbwAAAEoAAABVAAAAVQAAAHEAAABVAAAAVQAAAHEAAABVAAAAVQAAAG0AAABVAAAAiQAAAIkAAABvAAAAbwAAAHEAAABVAAAAbwAAAFUAAABxAAAAOwAAAHEAAABVAAAAUwAAAG8AAABVAAAAVwAAADsAAAA7AAAAcQAAAFUAAAA7AAAAcQAAADsAAAA7AAAAfgAAAG8AAACJAAAAiQAAAFUAAABVAAAAbQAAAFUAAABtAAAAbwAAAHEAAABVAAAAVQAAAFUAAABTAAAAVQAAAFUAAABkAAAAVQAAAFUAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAbQAAAIkAAACJAAAAOwAAADsAAABtAAAAOwAAAFUAAABVAAAAcQAAAFUAAAA7AAAAOwAAADkAAABvAAAAcAAAAHEAAAA2AAAANgAAADYAAAA2AAAAcQAAADYAAAA2AAAAVQAAAG8AAABtAAAAiQAAAIkAAABxAAAAVQAAAFUAAABVAAAAVQAAADsAAABXAAAAOwAAAHEAAABVAAAAcQAAAFUAAABVAAAAVQAAAFUAAABVAAAAcQAAAFUAAABVAAAAVQAAAHEAAAA2AAAAcQAAAFUAAACJAAAAiQAAAHEAAAA7AAAAOwAAADsAAAA7AAAAcQAAAFUAAABVAAAAVQAAAG8AAABxAAAANgAAADYAAAA2AAAANgAAAFUAAABxAAAANgAAADYAAABVAAAAVQAAAFUAAABxAAAANgAAAIkAAACJAAAAVQAAAFUAAABVAAAAVQAAAFMAAABVAAAAVQAAADsAAAA7AAAAVQAAAFUAAABxAAAAVQAAAFUAAABxAAAANgAAAHEAAABVAAAAcQAAADYAAAA2AAAAbwAAAFUAAABxAAAAiQAAAIkAAABvAAAAOwAAADsAAAA7AAAAcQAAADsAAABvAAAAVQAAAFMAAAA7AAAAOwAAAHEAAABVAAAAOwAAADkAAABVAAAAcQAAAG8AAABVAAAAVQAAAHEAAABVAAAAbwAAAHEAAACJAAAAiQAAAFUAAABxAAAAVQAAAFMAAABVAAAAUwAAAFUAAABvAAAAVQAAAFUAAAA5AAAAVQAAAFUAAABTAAAAVQAAADsAAABxAAAAVQAAADsAAABVAAAAcQAAAG8AAABVAAAAcQAAAIkAAACJAAAAbwAAAHEAAABVAAAAUwAAAFUAAABxAAAAOwAAAHEAAABvAAAAOwAAAHEAAABVAAAAOwAAAHEAAABVAAAAUwAAAFUAAABVAAAAUwAAAG8AAABxAAAAVQAAAG8AAABxAAAAiQAAAIkAAABxAAAAVQAAAFUAAABTAAAAbwAAAFUAAABVAAAAUwAAAFUAAABVAAAAcQAAADsAAABVAAAAUwAAAFUAAABTAAAAVQAAAG8AAABtAAAAVQAAAFMAAABvAAAAcQAAAFUAAACJAAAAiQAAAHEAAABvAAAAOwAAAD0AAABVAAAAbwAAAG8AAABtAAAAbwAAAG8AAABVAAAAVQAAAFUAAABxAAAAOwAAAHEAAABvAAAAbQAAAFUAAABvAAAAVQAAAH4AAABVAAAAbwAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAIkAAACJAAAAiQAAAA=="
    },
    {
      type = "objectgroup",
      name = "sorties",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1408,
          y = 1535,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1153,
          y = 1535,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 1535,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1025,
          y = 1535,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 959,
          y = 1535,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 897,
          y = 1534,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 639,
          y = 1536,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 577,
          y = 1535,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 1534,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 446,
          y = 1536,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 385,
          y = 1536,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 255,
          y = 1534,
          width = 66,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 1534,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 1535,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1536,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1471,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1408,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1279,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65,
          y = 1154,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 66,
          y = 1087,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65,
          y = 1024,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 897,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 768,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 703,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65,
          y = 640,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65,
          y = 450,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 320,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65,
          y = 255,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 189,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65,
          y = 126,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 65,
          y = 64,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 193,
          y = 64,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 64,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 383,
          y = 65,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 65,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 577,
          y = 64,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 644,
          y = 65,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 833,
          y = 64,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 894,
          y = 65,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1025,
          y = 64,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 64,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 64,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1279,
          y = 65,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1341,
          y = 65,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1404,
          y = 65,
          width = 67,
          height = 67,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1537,
          y = 64,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1537,
          y = 127,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1537,
          y = 190,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 384,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 512,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1537,
          y = 768,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1537,
          y = 896,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1538,
          y = 959,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1538,
          y = 1024,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1537,
          y = 1152,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 1216,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1538,
          y = 1279,
          width = 67,
          height = 67,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1537,
          y = 1346,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 1410,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "spawns_hunter",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 770,
          y = 640,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 638,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 704,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 766,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 768,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "spawns_ghost",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 382,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 1150,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 444,
          y = 1088,
          width = 66,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 450,
          y = 387,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
