return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.14.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 24,
  height = 24,
  tilewidth = 64,
  tileheight = 64,
  nextobjectid = 86,
  properties = {
     game_time = 90},
  tilesets = {
    {
      name = "couloirs 64px",
      firstgid = 1,
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "couloirs_64px.png",
      imagewidth = 832,
      imageheight = 832,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 169,
      tiles = {
        {
          id = 84,
          properties = {
            ["collidable"] = "true"
          }
        },
        {
          id = 97,
          properties = {
            ["collidable"] = "true"
          }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Calque de Tile 1",
      x = 0,
      y = 0,
      width = 24,
      height = 24,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "cQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAHEAAABxAAAAcQAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAHEAAABxAAAAVQAAAHEAAABVAAAAYgAAAGIAAABiAAAAVQAAAHEAAABxAAAAVQAAAGIAAABiAAAAYgAAAFUAAABxAAAAcQAAAFUAAABiAAAAYgAAAFUAAABxAAAAcQAAAHEAAABVAAAAVQAAAHEAAABiAAAAbwAAAG8AAABvAAAAVQAAAHEAAABxAAAAVQAAAG8AAABvAAAAbwAAAG8AAABxAAAAcQAAAFUAAABvAAAAbwAAAFUAAABxAAAAcQAAAHEAAABVAAAAVQAAAHEAAABvAAAAcQAAAHEAAABxAAAAVQAAAHEAAABxAAAAVQAAAHEAAABxAAAAcQAAAFUAAABxAAAAcQAAAG8AAABxAAAAcQAAAFUAAABxAAAAcQAAAHEAAABVAAAAVQAAAHEAAABVAAAAYgAAAFUAAABiAAAAYgAAAHEAAABxAAAAVQAAAHEAAABxAAAAcQAAAFUAAABxAAAAcQAAAFUAAABxAAAAcQAAAFUAAABxAAAAcQAAAHEAAABVAAAAVQAAAHEAAABVAAAAbwAAAGIAAABvAAAAbwAAAHEAAABxAAAAVQAAAHEAAABxAAAAcQAAAFUAAABxAAAAcQAAAFUAAABiAAAAYgAAAGIAAABVAAAAcQAAAHEAAABVAAAAVQAAAHEAAABVAAAAcQAAAG8AAABiAAAAcQAAAHEAAABxAAAAVQAAAHEAAABxAAAAcQAAAFUAAABxAAAAcQAAAFUAAABvAAAAbwAAAG8AAABiAAAAcQAAAHEAAABVAAAAVQAAAHEAAABVAAAAcQAAAHEAAABvAAAAVQAAAHEAAABxAAAAbwAAAHEAAABxAAAAcQAAAFUAAABxAAAAcQAAAFUAAABxAAAAcQAAAHEAAABvAAAAcQAAAHEAAABVAAAAVQAAAHEAAABiAAAAcQAAAFUAAABxAAAAYgAAAHEAAABxAAAAYgAAAGIAAABiAAAAYgAAAGIAAABxAAAAcQAAAGIAAABiAAAAYgAAAGIAAABiAAAAcQAAAHEAAABVAAAAVQAAAHEAAABvAAAAcQAAAFUAAABxAAAAbwAAAHEAAABxAAAAbwAAAG8AAABvAAAAbwAAAG8AAABxAAAAcQAAAG8AAABvAAAAbwAAAG8AAABvAAAAcQAAAHEAAABiAAAAYgAAAHEAAABiAAAAYgAAAGIAAABxAAAAcQAAAHEAAABxAAAAcQAAAHEAAABVAAAAcQAAAFUAAABiAAAAYgAAAFUAAABxAAAAYgAAAGIAAABiAAAAVQAAAHEAAABvAAAAbwAAAHEAAABvAAAAbwAAAG8AAABiAAAAYgAAAGIAAABxAAAAYgAAAGIAAABiAAAAcQAAAGIAAABvAAAAbwAAAGIAAABxAAAAbwAAAG8AAABvAAAAYgAAAHEAAABxAAAAcQAAAHEAAABxAAAAVQAAAHEAAABvAAAAbwAAAG8AAABxAAAAbwAAAG8AAABvAAAAcQAAAG8AAABxAAAAcQAAAG8AAABxAAAAcQAAAHEAAABxAAAAbwAAAHEAAABxAAAAVQAAAHEAAABxAAAAVQAAAHEAAABiAAAAYgAAAFUAAABiAAAAcQAAAFUAAABiAAAAYgAAAFUAAABxAAAAcQAAAFUAAABiAAAAcQAAAGIAAABVAAAAcQAAAFUAAABxAAAAVQAAAHEAAABxAAAAVQAAAHEAAABvAAAAbwAAAFUAAABvAAAAcQAAAFUAAABvAAAAbwAAAFUAAABxAAAAcQAAAFUAAABvAAAAYgAAAG8AAABVAAAAcQAAAFUAAABxAAAAVQAAAHEAAABxAAAAVQAAAHEAAABxAAAAcQAAAFUAAABxAAAAcQAAAFUAAABxAAAAcQAAAFUAAABxAAAAcQAAAFUAAABxAAAAbwAAAHEAAABVAAAAcQAAAGIAAABxAAAAVQAAAHEAAABxAAAAVQAAAHEAAABxAAAAcQAAAFUAAABxAAAAcQAAAFUAAABiAAAAcQAAAFUAAABxAAAAcQAAAFUAAABxAAAAcQAAAHEAAABVAAAAcQAAAG8AAABxAAAAVQAAAHEAAABxAAAAVQAAAHEAAABxAAAAcQAAAFUAAABxAAAAcQAAAFUAAABvAAAAcQAAAFUAAABxAAAAcQAAAFUAAABxAAAAcQAAAHEAAABVAAAAcQAAAFUAAABxAAAAVQAAAHEAAABxAAAAYgAAAHEAAABiAAAAYgAAAGIAAABxAAAAcQAAAGIAAABxAAAAcQAAAGIAAABxAAAAcQAAAGIAAABxAAAAcQAAAHEAAABiAAAAcQAAAFUAAABxAAAAVQAAAHEAAABxAAAAbwAAAHEAAABvAAAAbwAAAG8AAABxAAAAcQAAAG8AAABxAAAAcQAAAG8AAABxAAAAcQAAAG8AAABxAAAAcQAAAHEAAABvAAAAcQAAAGIAAABxAAAAVQAAAHEAAABxAAAAcQAAAHEAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAYgAAAGIAAABiAAAAcQAAAG8AAABxAAAAVQAAAHEAAABxAAAAcQAAAHEAAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAbwAAAG8AAABvAAAAcQAAAHEAAABxAAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAABxAAAAcQAAAHEAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAFUAAABVAAAAVQAAAHEAAABxAAAA"
    },
    {
      type = "objectgroup",
      name = "sorties",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1469,
          y = 1471,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1405,
          y = 1471,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 1407,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 575,
          y = 1472,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 513,
          y = 1471,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 833,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 768,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 62,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 0,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 0,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 63,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 704,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 832,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1474,
          y = 895,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1474,
          y = 960,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 1088,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 1152,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1474,
          y = 1215,
          width = 67,
          height = 67,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 1282,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 1346,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 638,
          y = 1472,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 1019,
          width = 67,
          height = 67,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 768,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1408.5,
          y = 1.16667,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "spawns_hunter",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 578,
          y = 704,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 574,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 832,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 638,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 768,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "spawns_ghost",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 318,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 1150,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 316,
          y = 1088,
          width = 66,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 322,
          y = 259,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
