return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.14.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 24,
  height = 24,
  tilewidth = 64,
  tileheight = 64,
  nextobjectid = 61,
  properties = {},
  tilesets = {
    {
      name = "couloirs 64px",
      firstgid = 1,
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "couloirs_64px.png",
      imagewidth = 832,
      imageheight = 832,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 169,
      tiles = {
        {
          id = 84,
          properties = {
            ["collidable"] = "true"
          }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Calque de Tile 1",
      x = 0,
      y = 0,
      width = 24,
      height = 24,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "UwAAAFUAAABTAAAAVQAAAG0AAABtAAAAbQAAAFUAAABtAAAAcQAAAFUAAABVAAAAOQAAADkAAABVAAAAVwAAAFUAAABxAAAAcQAAAHEAAABxAAAAcQAAAFUAAABtAAAAcQAAAFUAAABxAAAANgAAAG0AAABVAAAAbQAAADYAAABVAAAAcQAAADsAAAA7AAAAPQAAAFUAAABvAAAAcQAAADsAAABVAAAAcQAAAFUAAABVAAAAcQAAAFUAAABtAAAAcQAAADYAAABxAAAAVQAAAFUAAABvAAAAcQAAAFUAAABvAAAAVQAAAG0AAABVAAAAVwAAAFUAAABXAAAAVQAAAHEAAABvAAAAcQAAADsAAAA7AAAAVQAAAG8AAABtAAAAOQAAAFUAAABtAAAAbwAAADYAAABVAAAAcQAAADYAAABxAAAANgAAAFUAAAA7AAAAcQAAADsAAABxAAAAbwAAAFUAAABVAAAAUwAAAFUAAABxAAAAOwAAAHEAAABVAAAAcQAAADYAAABVAAAAcQAAAFUAAABVAAAAcQAAAFUAAABVAAAAcQAAAFUAAABxAAAAVQAAAFUAAABxAAAAVQAAAG8AAABvAAAAcQAAAFUAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAcQAAADYAAAA2AAAAcQAAADYAAABVAAAAcQAAAG8AAABxAAAAOwAAAFUAAABxAAAAbwAAAFUAAAA5AAAAVQAAADsAAAA7AAAAOwAAAHEAAAA7AAAAbwAAADsAAABVAAAAVQAAAHEAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAcQAAADsAAABVAAAAcQAAAFUAAABxAAAAbwAAAHEAAABVAAAAVQAAAFcAAABVAAAAVQAAAHEAAAA7AAAAbwAAAHEAAAA7AAAAVQAAADkAAAA2AAAANgAAADYAAABvAAAAcQAAAFUAAABVAAAAcQAAAG8AAABxAAAAVQAAAHEAAABvAAAAVQAAAFcAAABvAAAAVQAAAG0AAABVAAAAVQAAAFUAAABtAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAcQAAAFUAAABvAAAAVQAAAHEAAABVAAAAbwAAAFUAAABxAAAAVQAAAFUAAABVAAAAbwAAAG0AAAA7AAAAOwAAADsAAABVAAAAOwAAAHEAAABVAAAAOwAAADsAAABvAAAAVQAAADsAAAA5AAAAbwAAAHEAAABVAAAAbQAAADsAAABxAAAAbwAAAG8AAABVAAAAcQAAAFUAAABVAAAAVQAAAHEAAAA7AAAAcQAAAFUAAABVAAAAcQAAAFUAAABxAAAAbwAAAHEAAABVAAAAVQAAAFUAAAA7AAAAcQAAAFUAAABVAAAAVQAAAHEAAABVAAAAcQAAADsAAAA7AAAAVQAAAG0AAABVAAAAcQAAAFUAAAA7AAAAcQAAAG8AAAA5AAAAVQAAAD0AAAA7AAAAOwAAADsAAABxAAAAcQAAADsAAAA7AAAAOwAAAHEAAABvAAAAVQAAAFUAAABxAAAAOwAAAFUAAAA7AAAAcQAAAFUAAABxAAAAVQAAAFMAAABVAAAAbwAAAEoAAABVAAAAVQAAAHEAAABVAAAAVQAAAHEAAABVAAAAVQAAAG0AAABVAAAAbwAAAG8AAABxAAAAVQAAAG8AAABVAAAAcQAAADsAAABxAAAAVQAAAFMAAABvAAAAVQAAAFcAAAA7AAAAOwAAAHEAAABVAAAAOwAAAHEAAAA7AAAAOwAAAH4AAABvAAAAVQAAAFUAAABtAAAAVQAAAG0AAABvAAAAcQAAAFUAAABVAAAAVQAAAFMAAABVAAAAVQAAAGQAAABVAAAAVQAAAFUAAABVAAAAcQAAAFUAAABVAAAAVQAAAFUAAABtAAAAOwAAADsAAABtAAAAOwAAAFUAAABVAAAAcQAAAFUAAAA7AAAAOwAAADkAAABvAAAAcAAAAHEAAAA2AAAANgAAADYAAAA2AAAAcQAAADYAAAA2AAAAVQAAAG8AAABtAAAAcQAAAFUAAABVAAAAVQAAAFUAAAA7AAAAVwAAADsAAABxAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABxAAAANgAAAHEAAABVAAAAcQAAADsAAAA7AAAAOwAAADsAAABxAAAAVQAAAFUAAABVAAAAbwAAAHEAAAA2AAAANgAAADYAAAA2AAAAVQAAAHEAAAA2AAAANgAAAFUAAABVAAAAVQAAAHEAAAA2AAAAVQAAAFUAAABVAAAAVQAAAFMAAABVAAAAVQAAADsAAAA7AAAAVQAAAFUAAABxAAAAVQAAAFUAAABxAAAANgAAAHEAAABVAAAAcQAAADYAAAA2AAAAbwAAAFUAAABxAAAAbwAAADsAAAA7AAAAOwAAAHEAAAA7AAAAbwAAAFUAAABTAAAAOwAAADsAAABxAAAAVQAAADsAAAA5AAAAVQAAAHEAAABvAAAAVQAAAFUAAABxAAAAVQAAAG8AAABxAAAAVQAAAHEAAABVAAAAUwAAAFUAAABTAAAAVQAAAG8AAABVAAAAVQAAADkAAABVAAAAVQAAAFMAAABVAAAAOwAAAHEAAABVAAAAOwAAAFUAAABxAAAAbwAAAFUAAABxAAAAbwAAAHEAAABVAAAAUwAAAFUAAABxAAAAOwAAAHEAAABvAAAAOwAAAHEAAABVAAAAOwAAAHEAAABVAAAAUwAAAFUAAABVAAAAUwAAAG8AAABxAAAAVQAAAG8AAABxAAAAcQAAAFUAAABVAAAAUwAAAG8AAABVAAAAVQAAAFMAAABVAAAAVQAAAHEAAAA7AAAAVQAAAFMAAABVAAAAUwAAAFUAAABvAAAAbQAAAFUAAABTAAAAbwAAAHEAAABVAAAAcQAAAG8AAAA7AAAAPQAAAFUAAABvAAAAbwAAAG0AAABvAAAAbwAAAFUAAABVAAAAVQAAAHEAAAA7AAAAcQAAAG8AAABtAAAAVQAAAG8AAABVAAAAfgAAAFUAAABvAAAA"
    },
    {
      type = "objectgroup",
      name = "sorties",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {
        ["sorties"] = "true"
      },
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1344,
          y = 1471,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1089,
          y = 1471,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 1471,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 961,
          y = 1471,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 895,
          y = 1471,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 833,
          y = 1470,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 575,
          y = 1472,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 513,
          y = 1471,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1470,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 382,
          y = 1472,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 321,
          y = 1472,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 191,
          y = 1470,
          width = 66,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 1470,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 1471,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1472,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1407,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1344,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 1215,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 1090,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2,
          y = 1023,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 960,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 833,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 704,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 639,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 576,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 386,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 256,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 191,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 125,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 62,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1,
          y = 0,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 129,
          y = 0,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 0,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 319,
          y = 1,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 1,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 513,
          y = 0,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 580,
          y = 1,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 769,
          y = 0,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 830,
          y = 1,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 961,
          y = 0,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 0,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 0,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1215,
          y = 1,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1277,
          y = 1,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1340,
          y = 1,
          width = 67,
          height = 67,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 0,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 63,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 126,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 320,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 448,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 704,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 832,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1474,
          y = 895,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1474,
          y = 960,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 1088,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 1152,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1474,
          y = 1215,
          width = 67,
          height = 67,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1473,
          y = 1282,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 1346,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
