return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.14.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 24,
  height = 24,
  tilewidth = 64,
  tileheight = 64,
  nextobjectid = 1,
  properties = {},
  tilesets = {
    {
      name = "couloirs 64px",
      firstgid = 1,
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "couloirs_64px.png",
      imagewidth = 832,
      imageheight = 832,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 169,
      tiles = {
        {
          id = 84,
          properties = {
            ["collidable"] = "true"
          }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Calque de Tile 1",
      x = 0,
      y = 0,
      width = 24,
      height = 24,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "UwAAAFUAAABTAAAAVQAAAG0AAABtAAAAbQAAAFUAAABtAAAAcQAAAFUAAABVAAAAOQAAADkAAABVAAAAVwAAAFUAAABxAAAAcQAAAHEAAABxAAAAcQAAAFUAAABtAAAAcQAAAFUAAABxAAAANgAAAG0AAABVAAAAbQAAADYAAABVAAAAcQAAADsAAAA7AAAAPQAAAFUAAABvAAAAcQAAADsAAABVAAAAcQAAAFUAAABVAAAAcQAAAFUAAABtAAAAcQAAADYAAABxAAAAVQAAAFUAAABvAAAAcQAAAFUAAABvAAAAVQAAAG0AAABVAAAAVwAAAFUAAABXAAAAVQAAAHEAAABvAAAAcQAAADsAAAA7AAAAVQAAAG8AAABtAAAAOQAAAFUAAABtAAAAbwAAADYAAABVAAAAcQAAADYAAABxAAAANgAAAFUAAAA7AAAAcQAAADsAAABxAAAAbwAAAFUAAABVAAAAUwAAAFUAAABxAAAAOwAAAHEAAABVAAAAcQAAADYAAABVAAAAcQAAAFUAAABVAAAAcQAAAFUAAABVAAAAcQAAAFUAAABxAAAAVQAAAFUAAABxAAAAVQAAAG8AAABvAAAAcQAAAFUAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAcQAAADYAAAA2AAAAcQAAADYAAABVAAAAcQAAAG8AAABxAAAAOwAAAFUAAABxAAAAbwAAAFUAAAA5AAAAVQAAADsAAAA7AAAAOwAAAHEAAAA7AAAAbwAAADsAAABVAAAAVQAAAHEAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAcQAAADsAAABVAAAAcQAAAFUAAABxAAAAbwAAAHEAAABVAAAAVQAAAFcAAABVAAAAVQAAAHEAAAA7AAAAbwAAAHEAAAA7AAAAVQAAADkAAAA2AAAANgAAADYAAABvAAAAcQAAAFUAAABVAAAAcQAAAG8AAABxAAAAVQAAAHEAAABvAAAAVQAAAFcAAABvAAAAVQAAAG0AAABVAAAAVQAAAFUAAABtAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAcQAAAFUAAABvAAAAVQAAAHEAAABVAAAAbwAAAFUAAABxAAAAVQAAAFUAAABVAAAAbwAAAG0AAAA7AAAAOwAAADsAAABVAAAAOwAAAHEAAABVAAAAOwAAADsAAABvAAAAVQAAADsAAAA5AAAAbwAAAHEAAABVAAAAbQAAADsAAABxAAAAbwAAAG8AAABVAAAAcQAAAFUAAABVAAAAVQAAAHEAAAA7AAAAcQAAAFUAAABVAAAAcQAAAFUAAABxAAAAbwAAAHEAAABVAAAAVQAAAFUAAAA7AAAAcQAAAFUAAABVAAAAVQAAAHEAAABVAAAAcQAAADsAAAA7AAAAVQAAAG0AAABVAAAAcQAAAFUAAAA7AAAAcQAAAG8AAAA5AAAAVQAAAD0AAAA7AAAAOwAAADsAAABxAAAAcQAAADsAAAA7AAAAOwAAAHEAAABvAAAAVQAAAFUAAABxAAAAOwAAAFUAAAA7AAAAcQAAAFUAAABxAAAAVQAAAFMAAABVAAAAbwAAAEoAAABVAAAAVQAAAHEAAABVAAAAVQAAAHEAAABVAAAAVQAAAG0AAABVAAAAbwAAAG8AAABxAAAAVQAAAG8AAABVAAAAcQAAADsAAABxAAAAVQAAAFMAAABvAAAAVQAAAFcAAAA7AAAAOwAAAHEAAABVAAAAOwAAAHEAAAA7AAAAOwAAAH4AAABvAAAAVQAAAFUAAABtAAAAVQAAAG0AAABvAAAAcQAAAFUAAABVAAAAVQAAAFMAAABVAAAAVQAAAGQAAABVAAAAVQAAAFUAAABVAAAAcQAAAFUAAABVAAAAVQAAAFUAAABtAAAAOwAAADsAAABtAAAAOwAAAFUAAABVAAAAcQAAAFUAAAA7AAAAOwAAADkAAABvAAAAcAAAAHEAAAA2AAAANgAAADYAAAA2AAAAcQAAADYAAAA2AAAAVQAAAG8AAABtAAAAcQAAAFUAAABVAAAAVQAAAFUAAAA7AAAAVwAAADsAAABxAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABxAAAANgAAAHEAAABVAAAAcQAAADsAAAA7AAAAOwAAADsAAABxAAAAVQAAAFUAAABVAAAAbwAAAHEAAAA2AAAANgAAADYAAAA2AAAAVQAAAHEAAAA2AAAANgAAAFUAAABVAAAAVQAAAHEAAAA2AAAAVQAAAFUAAABVAAAAVQAAAFMAAABVAAAAVQAAADsAAAA7AAAAVQAAAFUAAABxAAAAVQAAAFUAAABxAAAANgAAAHEAAABVAAAAcQAAADYAAAA2AAAAbwAAAFUAAABxAAAAbwAAADsAAAA7AAAAOwAAAHEAAAA7AAAAbwAAAFUAAABTAAAAOwAAADsAAABxAAAAVQAAADsAAAA5AAAAVQAAAHEAAABvAAAAVQAAAFUAAABxAAAAVQAAAG8AAABxAAAAVQAAAHEAAABVAAAAUwAAAFUAAABTAAAAVQAAAG8AAABVAAAAVQAAADkAAABVAAAAVQAAAFMAAABVAAAAOwAAAHEAAABVAAAAOwAAAFUAAABxAAAAbwAAAFUAAABxAAAAbwAAAHEAAABVAAAAUwAAAFUAAABxAAAAOwAAAHEAAABvAAAAOwAAAHEAAABVAAAAOwAAAHEAAABVAAAAUwAAAFUAAABVAAAAUwAAAG8AAABxAAAAVQAAAG8AAABxAAAAcQAAAFUAAABVAAAAUwAAAG8AAABVAAAAVQAAAFMAAABVAAAAVQAAAHEAAAA7AAAAVQAAAFMAAABVAAAAUwAAAFUAAABvAAAAbQAAAFUAAABTAAAAbwAAAHEAAABVAAAAcQAAAG8AAAA7AAAAPQAAAFUAAABvAAAAbwAAAG0AAABvAAAAbwAAAFUAAABVAAAAVQAAAHEAAAA7AAAAcQAAAG8AAABtAAAAVQAAAG8AAABVAAAAfgAAAFUAAABvAAAA"
    }
  }
}
