return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "0.14.2",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 38,
  height = 38,
  tilewidth = 64,
  tileheight = 64,
  nextobjectid = 82,
  properties = {},
  tilesets = {
    {
      name = "couloirs 64px",
      firstgid = 1,
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      image = "couloirs_64px.png",
      imagewidth = 832,
      imageheight = 832,
      tileoffset = {
        x = 0,
        y = 0
      },
      properties = {},
      terrains = {},
      tilecount = 169,
      tiles = {
        {
          id = 84,
          properties = {
            ["collidable"] = "true"
          }
        },
        {
          id = 136,
          properties = {
            ["collidable"] = "true"
          }
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      name = "Calque de Tile 1",
      x = 0,
      y = 0,
      width = 38,
      height = 38,
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      data = "iQAAAKEAAACJAAAAiQAAAKEAAACJAAAAoQAAAKEAAACJAAAAoQAAAIkAAAChAAAAiQAAAKEAAAChAAAAoQAAAKEAAACJAAAAoQAAAIkAAACJAAAAoQAAAKEAAACJAAAAoQAAAIkAAACJAAAAoQAAAIkAAACJAAAAiQAAAKEAAAChAAAAiQAAAKEAAAChAAAAiQAAAKEAAACjAAAAiQAAAIkAAACjAAAAoQAAAIkAAAChAAAAiQAAAKMAAAChAAAAowAAAIkAAACjAAAAoQAAAIkAAACJAAAAoQAAAKMAAAChAAAAowAAAIkAAAChAAAAiQAAAKMAAAChAAAAowAAAIkAAAChAAAAowAAAKMAAACJAAAAoQAAAIkAAACJAAAAoQAAAIkAAACJAAAAiQAAAIkAAACjAAAAowAAAKEAAACJAAAAowAAAKEAAACJAAAAoQAAAIkAAAChAAAAiQAAAIkAAAChAAAAowAAAKMAAAChAAAAiQAAAIkAAAChAAAAowAAAIkAAACJAAAAoQAAAIkAAAChAAAAowAAAKEAAACJAAAAoQAAAKMAAAChAAAAowAAAKMAAACJAAAAiQAAAKMAAACjAAAAowAAAIkAAACJAAAAoQAAAKMAAACJAAAAiQAAAKMAAAChAAAAowAAAKEAAACjAAAAiQAAAKEAAACJAAAAiQAAAKEAAACjAAAAowAAAKEAAAChAAAAowAAAIkAAACJAAAAiQAAAKEAAACJAAAAoQAAAIkAAAChAAAAiQAAAKEAAACJAAAAiQAAAKMAAACjAAAAoQAAAIkAAAChAAAAowAAAKMAAACJAAAAoQAAAKMAAACJAAAAoQAAAIkAAACJAAAAoQAAAIkAAACjAAAAoQAAAKMAAACJAAAAiQAAAIkAAAChAAAAiQAAAKEAAACJAAAAiQAAAKMAAACjAAAAoQAAAIkAAAChAAAAiQAAAIkAAACjAAAAoQAAAKMAAACjAAAAoQAAAIkAAACJAAAAowAAAIkAAACJAAAAoQAAAIkAAAChAAAAiQAAAKMAAAChAAAAowAAAIkAAAChAAAAowAAAKEAAACJAAAAoQAAAKMAAACjAAAAiQAAAKEAAACJAAAAoQAAAKMAAACJAAAAoQAAAIkAAAChAAAAiQAAAKEAAACjAAAAowAAAIkAAAChAAAAiQAAAIkAAAChAAAAowAAAKMAAACJAAAAowAAAIkAAAChAAAAowAAAKEAAACJAAAAoQAAAIkAAAChAAAAiQAAAKEAAACJAAAAiQAAAIkAAAChAAAAiQAAAIkAAACjAAAAoQAAAIkAAACJAAAAoQAAAIkAAAChAAAAiQAAAIkAAACJAAAAiQAAAIkAAAChAAAAiQAAAKEAAACjAAAAiQAAAIkAAAChAAAAiQAAAIkAAAChAAAAowAAAKEAAACJAAAAoQAAAKMAAACJAAAAowAAAFUAAACjAAAAVQAAAKMAAACjAAAAowAAAFUAAACjAAAAowAAAFUAAABVAAAAowAAAKMAAABVAAAAowAAAFUAAACjAAAAowAAAKMAAACjAAAAowAAAFUAAACjAAAAiQAAAKEAAACjAAAAowAAAKEAAACJAAAAowAAAIkAAACJAAAAoQAAAKMAAACJAAAAiQAAAIkAAABxAAAAVQAAAHEAAAA2AAAAbQAAAFUAAABtAAAANgAAAFUAAABxAAAAOwAAADsAAAA9AAAAVQAAAG8AAABxAAAAOwAAAFUAAABxAAAAVQAAAFUAAABxAAAAVQAAAG0AAACJAAAAoQAAAIkAAAChAAAAiQAAAKMAAAChAAAAowAAAKMAAAChAAAAoQAAAKMAAACjAAAAiQAAAHEAAAA2AAAAcQAAAFUAAABVAAAAbwAAAHEAAABVAAAAbwAAAFUAAABtAAAAVQAAAFcAAABVAAAAVwAAAFUAAABxAAAAbwAAAHEAAAA7AAAAOwAAAFUAAABvAAAAbQAAAIkAAAChAAAAowAAAKEAAACJAAAAiQAAAIkAAAChAAAAiQAAAKEAAACJAAAAiQAAAKEAAACJAAAAOQAAAFUAAABtAAAAbwAAADYAAABVAAAAcQAAADYAAABxAAAANgAAAFUAAAA7AAAAcQAAADsAAABxAAAAbwAAAFUAAABVAAAAUwAAAFUAAABxAAAAOwAAAHEAAABVAAAAowAAAKEAAACJAAAAoQAAAKMAAACJAAAAowAAAKEAAACJAAAAoQAAAKMAAACjAAAAoQAAAIkAAABxAAAANgAAAFUAAABxAAAAVQAAAFUAAABxAAAAVQAAAFUAAABxAAAAVQAAAHEAAABVAAAAVQAAAHEAAABVAAAAbwAAAG8AAABxAAAAVQAAAFUAAABVAAAAcQAAAFUAAAChAAAAiQAAAKMAAAChAAAAiQAAAKMAAAChAAAAiQAAAIkAAAChAAAAiQAAAIkAAAChAAAAowAAAFUAAABVAAAAVQAAAHEAAAA2AAAANgAAAHEAAAA2AAAAVQAAAHEAAABvAAAAcQAAADsAAABVAAAAcQAAAG8AAABVAAAAOQAAAFUAAAA7AAAAOwAAADsAAABxAAAAOwAAAIkAAACjAAAAoQAAAIkAAACJAAAAoQAAAIkAAACjAAAAowAAAKEAAACjAAAAiQAAAKEAAACJAAAAbwAAADsAAABVAAAAVQAAAHEAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAcQAAADsAAABVAAAAcQAAAFUAAABxAAAAbwAAAHEAAABVAAAAVQAAAFcAAABVAAAAowAAAKEAAACJAAAAowAAAKMAAAChAAAAowAAAKEAAACJAAAAiQAAAKEAAACJAAAAiQAAAKMAAABVAAAAcQAAADsAAABvAAAAcQAAADsAAABVAAAAOQAAADYAAAA2AAAANgAAAG8AAABxAAAAVQAAAFUAAABxAAAAbwAAAHEAAABVAAAAcQAAAG8AAABVAAAAVwAAAG8AAACJAAAAoQAAAKMAAACJAAAAoQAAAIkAAAChAAAAoQAAAKMAAACjAAAAoQAAAKMAAACjAAAAoQAAAFUAAABtAAAAVQAAAFUAAABVAAAAbQAAAFUAAABxAAAAVQAAAFUAAABVAAAAVQAAAHEAAABVAAAAbwAAAFUAAABxAAAAVQAAAG8AAABVAAAAcQAAAFUAAABVAAAAVQAAAKMAAAChAAAAiQAAAKMAAAChAAAAiQAAAIkAAACJAAAAiQAAAKEAAACJAAAAiQAAAKEAAACJAAAAbwAAAG0AAAA7AAAAOwAAADsAAABVAAAAOwAAAHEAAABVAAAAOwAAADsAAABvAAAAVQAAADsAAAA5AAAAbwAAAHEAAABVAAAAbQAAADsAAABxAAAAbwAAAG8AAABVAAAAoQAAAIkAAACJAAAAiQAAAKEAAACjAAAAiQAAAKMAAACJAAAAoQAAAKMAAACJAAAAiQAAAIkAAABxAAAAVQAAAFUAAABVAAAAcQAAADsAAABxAAAAVQAAAFUAAABxAAAAVQAAAHEAAABvAAAAcQAAAFUAAABVAAAAVQAAADsAAABxAAAAVQAAAFUAAABVAAAAcQAAAFUAAAChAAAAowAAAKMAAACJAAAAoQAAAIkAAACjAAAAiQAAAKMAAAChAAAAiQAAAKMAAACjAAAAiQAAAHEAAAA7AAAAOwAAAFUAAABtAAAAVQAAAHEAAABVAAAAOwAAAHEAAABvAAAAOQAAAFUAAAA9AAAAOwAAADsAAAA7AAAAcQAAAHEAAAA7AAAAOwAAADsAAABxAAAAbwAAAIkAAAChAAAAiQAAAKMAAAChAAAAowAAAKEAAACjAAAAoQAAAIkAAACJAAAAiQAAAKEAAACjAAAAVQAAAFUAAABxAAAAOwAAAFUAAAA7AAAAcQAAAFUAAABxAAAAVQAAAFMAAABVAAAAbwAAAEoAAABVAAAAVQAAAHEAAABVAAAAVQAAAHEAAABVAAAAVQAAAG0AAABVAAAAowAAAKEAAACjAAAAiQAAAKEAAACJAAAAiQAAAKEAAACJAAAAiQAAAKMAAACjAAAAoQAAAIkAAABvAAAAbwAAAHEAAABVAAAAbwAAAFUAAABxAAAAOwAAAHEAAABVAAAAUwAAAG8AAABVAAAAVwAAADsAAAA7AAAAcQAAAFUAAAA7AAAAcQAAADsAAAA7AAAAfgAAAG8AAACJAAAAoQAAAKEAAACjAAAAoQAAAKMAAACjAAAAoQAAAKMAAACjAAAAoQAAAIkAAAChAAAAowAAAFUAAABVAAAAbQAAAFUAAABtAAAAbwAAAHEAAABVAAAAVQAAAFUAAABTAAAAVQAAAFUAAABkAAAAVQAAAFUAAABVAAAAVQAAAHEAAABVAAAAVQAAAFUAAABVAAAAbQAAAIkAAACJAAAAoQAAAIkAAAChAAAAiQAAAKEAAACJAAAAiQAAAIkAAAChAAAAowAAAKEAAACJAAAAOwAAADsAAABtAAAAOwAAAFUAAABVAAAAcQAAAFUAAAA7AAAAOwAAADkAAABvAAAAcAAAAHEAAAA2AAAANgAAADYAAAA2AAAAcQAAADYAAAA2AAAAVQAAAG8AAABtAAAAiQAAAKMAAAChAAAAowAAAKEAAACjAAAAiQAAAKMAAACjAAAAiQAAAKEAAACJAAAAiQAAAIkAAABxAAAAVQAAAFUAAABVAAAAVQAAADsAAABXAAAAOwAAAHEAAABVAAAAcQAAAFUAAABVAAAAVQAAAFUAAABVAAAAcQAAAFUAAABVAAAAVQAAAHEAAAA2AAAAcQAAAFUAAACjAAAAoQAAAIkAAACJAAAAoQAAAIkAAACJAAAAiQAAAKEAAACJAAAAiQAAAKMAAACjAAAAiQAAAHEAAAA7AAAAOwAAADsAAAA7AAAAcQAAAFUAAABVAAAAVQAAAG8AAABxAAAANgAAADYAAAA2AAAANgAAAFUAAABxAAAANgAAADYAAABVAAAAVQAAAFUAAABxAAAANgAAAIkAAAChAAAAowAAAKMAAACJAAAAowAAAKMAAACjAAAAiQAAAKMAAACjAAAAoQAAAKEAAACjAAAAVQAAAFUAAABVAAAAVQAAAFMAAABVAAAAVQAAADsAAAA7AAAAVQAAAFUAAABxAAAAVQAAAFUAAABxAAAANgAAAHEAAABVAAAAcQAAADYAAAA2AAAAbwAAAFUAAABxAAAAiQAAAIkAAACJAAAAiQAAAKMAAAChAAAAiQAAAKEAAACjAAAAoQAAAKEAAACJAAAAiQAAAIkAAABvAAAAOwAAADsAAAA7AAAAcQAAADsAAABvAAAAVQAAAFMAAAA7AAAAOwAAAHEAAABVAAAAOwAAADkAAABVAAAAcQAAAG8AAABVAAAAVQAAAHEAAABVAAAAbwAAAHEAAACJAAAAowAAAIkAAACjAAAAoQAAAIkAAACjAAAAiQAAAIkAAACJAAAAoQAAAIkAAACjAAAAowAAAFUAAABxAAAAVQAAAFMAAABVAAAAUwAAAFUAAABvAAAAVQAAAFUAAAA5AAAAVQAAAFUAAABTAAAAVQAAADsAAABxAAAAVQAAADsAAABVAAAAcQAAAG8AAABVAAAAcQAAAIkAAAChAAAAowAAAKEAAAChAAAAowAAAIkAAACjAAAAowAAAKMAAAChAAAAowAAAIkAAACJAAAAbwAAAHEAAABVAAAAUwAAAFUAAABxAAAAOwAAAHEAAABvAAAAOwAAAHEAAABVAAAAOwAAAHEAAABVAAAAUwAAAFUAAABVAAAAUwAAAG8AAABxAAAAVQAAAG8AAABxAAAAiQAAAIkAAAChAAAAiQAAAIkAAAChAAAAiQAAAIkAAAChAAAAiQAAAKEAAACJAAAAowAAAIkAAABxAAAAVQAAAFUAAABTAAAAbwAAAFUAAABVAAAAUwAAAFUAAABVAAAAcQAAADsAAABVAAAAUwAAAFUAAABTAAAAVQAAAG8AAABtAAAAVQAAAFMAAABvAAAAcQAAAFUAAACjAAAAowAAAKEAAACjAAAAowAAAIkAAACjAAAAowAAAKEAAACJAAAAoQAAAKMAAAChAAAAiQAAAHEAAABvAAAAOwAAAD0AAABVAAAAbwAAAG8AAABtAAAAbwAAAG8AAABVAAAAVQAAAFUAAABxAAAAOwAAAHEAAABvAAAAbQAAAFUAAABvAAAAVQAAAH4AAABVAAAAbwAAAIkAAAChAAAAiQAAAIkAAAChAAAAowAAAKEAAACJAAAAoQAAAKMAAAChAAAAiQAAAIkAAACjAAAAiQAAAIkAAACJAAAAiQAAAKMAAACJAAAAiQAAAIkAAACJAAAAiQAAAKMAAACjAAAAowAAAIkAAACJAAAAiQAAAIkAAACJAAAAowAAAIkAAACjAAAAiQAAAKMAAACJAAAAowAAAKEAAACjAAAAowAAAKEAAACJAAAAoQAAAIkAAAChAAAAiQAAAKEAAAChAAAAiQAAAKEAAACJAAAAowAAAKMAAACjAAAAoQAAAKMAAACjAAAAiQAAAKMAAACjAAAAiQAAAIkAAAChAAAAowAAAKMAAACJAAAAowAAAKMAAAChAAAAiQAAAKEAAACJAAAAoQAAAKMAAAChAAAAiQAAAKEAAACJAAAAoQAAAKMAAAChAAAAowAAAKEAAACJAAAAoQAAAIkAAACjAAAAoQAAAIkAAAChAAAAiQAAAKEAAACJAAAAoQAAAKEAAACjAAAAiQAAAKEAAACJAAAAowAAAKEAAACJAAAAoQAAAIkAAAChAAAAiQAAAKEAAACJAAAAoQAAAIkAAACJAAAAiQAAAKEAAACJAAAAoQAAAKMAAACJAAAAoQAAAIkAAAChAAAAiQAAAKMAAAChAAAAowAAAKEAAACJAAAAowAAAIkAAACjAAAAoQAAAKMAAACJAAAAiQAAAKEAAACjAAAAoQAAAIkAAAChAAAAiQAAAIkAAAChAAAAoQAAAKEAAACjAAAAiQAAAIkAAAChAAAAowAAAKMAAACjAAAAoQAAAKMAAAChAAAAiQAAAKMAAAChAAAAiQAAAKEAAACjAAAAiQAAAKEAAACJAAAAoQAAAKMAAAChAAAAiQAAAKEAAACJAAAAoQAAAIkAAACjAAAAoQAAAKEAAACJAAAAowAAAKEAAACjAAAAowAAAIkAAACJAAAAoQAAAIkAAACjAAAAowAAAKEAAACJAAAAoQAAAIkAAAChAAAAiQAAAKEAAACjAAAAiQAAAKEAAACjAAAAiQAAAIkAAACjAAAAoQAAAIkAAACJAAAAoQAAAIkAAACJAAAAoQAAAKMAAAChAAAAowAAAIkAAACJAAAAiQAAAKMAAAChAAAAiQAAAIkAAAChAAAAowAAAKMAAACJAAAAoQAAAKEAAACJAAAAoQAAAKMAAAChAAAAiQAAAKEAAACJAAAAiQAAAKEAAACJAAAAiQAAAKEAAACjAAAAiQAAAKEAAACJAAAAowAAAIkAAAChAAAAiQAAAKMAAACJAAAAiQAAAKEAAACJAAAAowAAAKMAAACjAAAAoQAAAKEAAACjAAAAowAAAIkAAACJAAAAiQAAAKMAAAChAAAAiQAAAKMAAACJAAAAoQAAAIkAAACJAAAAoQAAAIkAAACjAAAAoQAAAIkAAACjAAAAiQAAAA=="
    },
    {
      type = "objectgroup",
      name = "sorties",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1792,
          y = 1919,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1537,
          y = 1919,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1472,
          y = 1919,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1409,
          y = 1919,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1343,
          y = 1919,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1281,
          y = 1918,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1023,
          y = 1920,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 961,
          y = 1919,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 1918,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 830,
          y = 1920,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 769,
          y = 1920,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 639,
          y = 1918,
          width = 66,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 1918,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 1919,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1920,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1855,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1792,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1663,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 449,
          y = 1538,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 21,
          name = "",
          type = "",
          shape = "rectangle",
          x = 450,
          y = 1471,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 449,
          y = 1408,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1281,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1152,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 1087,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 449,
          y = 1024,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 449,
          y = 834,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 704,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 449,
          y = 639,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 573,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 449,
          y = 510,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "",
          shape = "rectangle",
          x = 449,
          y = 448,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 577,
          y = 448,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 448,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 35,
          name = "",
          type = "",
          shape = "rectangle",
          x = 767,
          y = 449,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 449,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 961,
          y = 448,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1028,
          y = 449,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1217,
          y = 448,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1278,
          y = 449,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1409,
          y = 448,
          width = 61,
          height = 61,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 448,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1600,
          y = 448,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1663,
          y = 449,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1725,
          y = 449,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1788,
          y = 449,
          width = 67,
          height = 67,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1921,
          y = 448,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1921,
          y = 511,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1921,
          y = 574,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 768,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 896,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1921,
          y = 1152,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1921,
          y = 1280,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1922,
          y = 1343,
          width = 65,
          height = 65,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1922,
          y = 1408,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1921,
          y = 1536,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 1600,
          width = 63,
          height = 63,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1922,
          y = 1663,
          width = 67,
          height = 67,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1921,
          y = 1730,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 60,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 1794,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "spawns_hunter",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1154,
          y = 1024,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 1022,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 1088,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1152,
          y = 1150,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 1152,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      name = "spawns_ghost",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 766,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1536,
          y = 1534,
          width = 62,
          height = 62,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 828,
          y = 1472,
          width = 66,
          height = 66,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 834,
          y = 771,
          width = 60,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
